// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BaseConfigInitParameters struct {
}

type BaseConfigObservation struct {

	// (Boolean) Whether idle scaling is enabled while the window is active.
	IdleScaling *bool `json:"idleScaling,omitempty" tf:"idle_scaling,omitempty"`

	// (Number) Minutes of inactivity before the service scales to zero. Must be at least 5. Only meaningful when idle_scaling is true.
	IdleTimeoutMinutes *float64 `json:"idleTimeoutMinutes,omitempty" tf:"idle_timeout_minutes,omitempty"`

	// (Number) Maximum memory per replica in GiB. Must be set together with min_replica_memory_gb.
	MaxReplicaMemoryGb *float64 `json:"maxReplicaMemoryGb,omitempty" tf:"max_replica_memory_gb,omitempty"`

	// (Number) Maximum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	MaxReplicas *float64 `json:"maxReplicas,omitempty" tf:"max_replicas,omitempty"`

	// (Number) Minimum memory per replica in GiB. Must be set together with max_replica_memory_gb.
	MinReplicaMemoryGb *float64 `json:"minReplicaMemoryGb,omitempty" tf:"min_replica_memory_gb,omitempty"`

	// (Number) Minimum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	MinReplicas *float64 `json:"minReplicas,omitempty" tf:"min_replicas,omitempty"`
}

type BaseConfigParameters struct {
}

type EntriesInitParameters struct {

	// accepts 1–24.
	// End hour in UTC (1-24). Must differ from start_hour_utc. Note the asymmetric range: end_hour_utc=0 is invalid; use end_hour_utc=24 to mean midnight at end of day.
	EndHourUtc *float64 `json:"endHourUtc,omitempty" tf:"end_hour_utc,omitempty"`

	// (Boolean) Whether idle scaling is enabled while the window is active.
	// Whether idle scaling is enabled while the window is active.
	IdleScaling *bool `json:"idleScaling,omitempty" tf:"idle_scaling,omitempty"`

	// (Number) Minutes of inactivity before the service scales to zero. Must be at least 5. Only meaningful when idle_scaling is true.
	// Minutes of inactivity before the service scales to zero. Must be at least 5. Only meaningful when idle_scaling is true.
	IdleTimeoutMinutes *float64 `json:"idleTimeoutMinutes,omitempty" tf:"idle_timeout_minutes,omitempty"`

	// (Number) Maximum memory per replica in GiB. Must be set together with min_replica_memory_gb.
	// Maximum memory per replica in GiB. Must be set together with min_replica_memory_gb.
	MaxReplicaMemoryGb *float64 `json:"maxReplicaMemoryGb,omitempty" tf:"max_replica_memory_gb,omitempty"`

	// (Number) Maximum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	// Maximum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	MaxReplicas *float64 `json:"maxReplicas,omitempty" tf:"max_replicas,omitempty"`

	// (Number) Minimum memory per replica in GiB. Must be set together with max_replica_memory_gb.
	// Minimum memory per replica in GiB. Must be set together with max_replica_memory_gb.
	MinReplicaMemoryGb *float64 `json:"minReplicaMemoryGb,omitempty" tf:"min_replica_memory_gb,omitempty"`

	// (Number) Minimum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	// Minimum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	MinReplicas *float64 `json:"minReplicas,omitempty" tf:"min_replicas,omitempty"`

	// readable name for the entry (e.g. "Business hours").
	// Human-readable name for the entry (e.g. "Business hours").
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// accepts 0–23.
	// Start hour in UTC (0-23). If end_hour_utc < start_hour_utc the window wraps overnight. Set start_hour_utc=0 and end_hour_utc=24 for a 24-hour window.
	StartHourUtc *float64 `json:"startHourUtc,omitempty" tf:"start_hour_utc,omitempty"`

	// (Set of Number) Weekdays this entry covers. 0 = Sunday … 6 = Saturday.
	// Weekdays this entry covers. 0 = Sunday … 6 = Saturday.
	// +listType=set
	Weekdays []*float64 `json:"weekdays,omitempty" tf:"weekdays,omitempty"`
}

type EntriesObservation struct {

	// accepts 1–24.
	// End hour in UTC (1-24). Must differ from start_hour_utc. Note the asymmetric range: end_hour_utc=0 is invalid; use end_hour_utc=24 to mean midnight at end of day.
	EndHourUtc *float64 `json:"endHourUtc,omitempty" tf:"end_hour_utc,omitempty"`

	// (Boolean) Whether idle scaling is enabled while the window is active.
	// Whether idle scaling is enabled while the window is active.
	IdleScaling *bool `json:"idleScaling,omitempty" tf:"idle_scaling,omitempty"`

	// (Number) Minutes of inactivity before the service scales to zero. Must be at least 5. Only meaningful when idle_scaling is true.
	// Minutes of inactivity before the service scales to zero. Must be at least 5. Only meaningful when idle_scaling is true.
	IdleTimeoutMinutes *float64 `json:"idleTimeoutMinutes,omitempty" tf:"idle_timeout_minutes,omitempty"`

	// (Number) Maximum memory per replica in GiB. Must be set together with min_replica_memory_gb.
	// Maximum memory per replica in GiB. Must be set together with min_replica_memory_gb.
	MaxReplicaMemoryGb *float64 `json:"maxReplicaMemoryGb,omitempty" tf:"max_replica_memory_gb,omitempty"`

	// (Number) Maximum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	// Maximum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	MaxReplicas *float64 `json:"maxReplicas,omitempty" tf:"max_replicas,omitempty"`

	// (Number) Minimum memory per replica in GiB. Must be set together with max_replica_memory_gb.
	// Minimum memory per replica in GiB. Must be set together with max_replica_memory_gb.
	MinReplicaMemoryGb *float64 `json:"minReplicaMemoryGb,omitempty" tf:"min_replica_memory_gb,omitempty"`

	// (Number) Minimum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	// Minimum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	MinReplicas *float64 `json:"minReplicas,omitempty" tf:"min_replicas,omitempty"`

	// readable name for the entry (e.g. "Business hours").
	// Human-readable name for the entry (e.g. "Business hours").
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// accepts 0–23.
	// Start hour in UTC (0-23). If end_hour_utc < start_hour_utc the window wraps overnight. Set start_hour_utc=0 and end_hour_utc=24 for a 24-hour window.
	StartHourUtc *float64 `json:"startHourUtc,omitempty" tf:"start_hour_utc,omitempty"`

	// (Set of Number) Weekdays this entry covers. 0 = Sunday … 6 = Saturday.
	// Weekdays this entry covers. 0 = Sunday … 6 = Saturday.
	// +listType=set
	Weekdays []*float64 `json:"weekdays,omitempty" tf:"weekdays,omitempty"`
}

type EntriesParameters struct {

	// accepts 1–24.
	// End hour in UTC (1-24). Must differ from start_hour_utc. Note the asymmetric range: end_hour_utc=0 is invalid; use end_hour_utc=24 to mean midnight at end of day.
	// +kubebuilder:validation:Optional
	EndHourUtc *float64 `json:"endHourUtc" tf:"end_hour_utc,omitempty"`

	// (Boolean) Whether idle scaling is enabled while the window is active.
	// Whether idle scaling is enabled while the window is active.
	// +kubebuilder:validation:Optional
	IdleScaling *bool `json:"idleScaling,omitempty" tf:"idle_scaling,omitempty"`

	// (Number) Minutes of inactivity before the service scales to zero. Must be at least 5. Only meaningful when idle_scaling is true.
	// Minutes of inactivity before the service scales to zero. Must be at least 5. Only meaningful when idle_scaling is true.
	// +kubebuilder:validation:Optional
	IdleTimeoutMinutes *float64 `json:"idleTimeoutMinutes,omitempty" tf:"idle_timeout_minutes,omitempty"`

	// (Number) Maximum memory per replica in GiB. Must be set together with min_replica_memory_gb.
	// Maximum memory per replica in GiB. Must be set together with min_replica_memory_gb.
	// +kubebuilder:validation:Optional
	MaxReplicaMemoryGb *float64 `json:"maxReplicaMemoryGb,omitempty" tf:"max_replica_memory_gb,omitempty"`

	// (Number) Maximum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	// Maximum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	// +kubebuilder:validation:Optional
	MaxReplicas *float64 `json:"maxReplicas,omitempty" tf:"max_replicas,omitempty"`

	// (Number) Minimum memory per replica in GiB. Must be set together with max_replica_memory_gb.
	// Minimum memory per replica in GiB. Must be set together with max_replica_memory_gb.
	// +kubebuilder:validation:Optional
	MinReplicaMemoryGb *float64 `json:"minReplicaMemoryGb,omitempty" tf:"min_replica_memory_gb,omitempty"`

	// (Number) Minimum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	// Minimum replica count while the window is active. Currently the server requires min_replicas == max_replicas.
	// +kubebuilder:validation:Optional
	MinReplicas *float64 `json:"minReplicas,omitempty" tf:"min_replicas,omitempty"`

	// readable name for the entry (e.g. "Business hours").
	// Human-readable name for the entry (e.g. "Business hours").
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// accepts 0–23.
	// Start hour in UTC (0-23). If end_hour_utc < start_hour_utc the window wraps overnight. Set start_hour_utc=0 and end_hour_utc=24 for a 24-hour window.
	// +kubebuilder:validation:Optional
	StartHourUtc *float64 `json:"startHourUtc" tf:"start_hour_utc,omitempty"`

	// (Set of Number) Weekdays this entry covers. 0 = Sunday … 6 = Saturday.
	// Weekdays this entry covers. 0 = Sunday … 6 = Saturday.
	// +kubebuilder:validation:Optional
	// +listType=set
	Weekdays []*float64 `json:"weekdays" tf:"weekdays,omitempty"`
}

type ScheduledScalingInitParameters struct {

	// (Attributes Set) Recurring scaling windows. The server rejects any pair of entries that overlap in time, so at most one window is active at any moment; otherwise base_config applies. (see below for nested schema)
	Entries []EntriesInitParameters `json:"entries,omitempty" tf:"entries,omitempty"`
}

type ScheduledScalingObservation struct {

	// managed. (see below for nested schema)
	BaseConfig *BaseConfigObservation `json:"baseConfig,omitempty" tf:"base_config,omitempty"`

	// (Attributes Set) Recurring scaling windows. The server rejects any pair of entries that overlap in time, so at most one window is active at any moment; otherwise base_config applies. (see below for nested schema)
	Entries []EntriesObservation `json:"entries,omitempty" tf:"entries,omitempty"`

	// (String) Resource identifier. Equal to service_id (one schedule per service).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ScheduledScalingParameters struct {

	// (Attributes Set) Recurring scaling windows. The server rejects any pair of entries that overlap in time, so at most one window is active at any moment; otherwise base_config applies. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Entries []EntriesParameters `json:"entries,omitempty" tf:"entries,omitempty"`
}

// ScheduledScalingSpec defines the desired state of ScheduledScaling
type ScheduledScalingSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ScheduledScalingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScheduledScalingInitParameters `json:"initProvider,omitempty"`
}

// ScheduledScalingStatus defines the observed state of ScheduledScaling.
type ScheduledScalingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ScheduledScalingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ScheduledScaling is the Schema for the ScheduledScalings API. You can use the clickhouse_service_scheduled_scaling resource to manage time-based scaling rules for a ClickHouse Cloud service. A schedule is a set of recurring weekly windows. The server rejects any pair of entries that overlap in time, so at most one window is active at any moment. While a window is active the service uses the replica count, memory bounds, and idle-scaling settings declared on that entry; otherwise the service falls back to its base auto-scaling configuration. ~> Note: This resource is in alpha. Scheduled scaling must be enabled for your organization (canUseScheduledAutoscaling). Reach out to ClickHouse support if the API returns 403 FORBIDDEN. The server currently requires min_replicas == max_replicas per entry, and a maximum of 10 entries per schedule. Hour ranges Hour ranges are asymmetric: start_hour_utc accepts 0–23.end_hour_utc accepts 1–24.start_hour_utc and end_hour_utc must differ.Set start_hour_utc = 0 and end_hour_utc = 24 for a 24-hour window.Set end_hour_utc < start_hour_utc to wrap overnight (e.g. 22 to 6 covers 22:00–06:00 next day). Example Usage
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,clickhouse}
type ScheduledScaling struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.entries) || (has(self.initProvider) && has(self.initProvider.entries))",message="spec.forProvider.entries is a required parameter"
	Spec   ScheduledScalingSpec   `json:"spec"`
	Status ScheduledScalingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScheduledScalingList contains a list of ScheduledScalings
type ScheduledScalingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ScheduledScaling `json:"items"`
}

// Repository type metadata.
var (
	ScheduledScaling_Kind             = "ScheduledScaling"
	ScheduledScaling_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ScheduledScaling_Kind}.String()
	ScheduledScaling_KindAPIVersion   = ScheduledScaling_Kind + "." + CRDGroupVersion.String()
	ScheduledScaling_GroupVersionKind = CRDGroupVersion.WithKind(ScheduledScaling_Kind)
)

func init() {
	SchemeBuilder.Register(&ScheduledScaling{}, &ScheduledScalingList{})
}
