// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type TransparentDataEncryptionKeyAssociationInitParameters struct {

	// (String) ID of the Encryption key to use for data encryption. Must be an ARN for AWS services or a Key Resource Path for GCP services.
	// ID of the Encryption key to use for data encryption. Must be an ARN for AWS services or a Key Resource Path for GCP services.
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`
}

type TransparentDataEncryptionKeyAssociationObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) ID of the Encryption key to use for data encryption. Must be an ARN for AWS services or a Key Resource Path for GCP services.
	// ID of the Encryption key to use for data encryption. Must be an ARN for AWS services or a Key Resource Path for GCP services.
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`
}

type TransparentDataEncryptionKeyAssociationParameters struct {

	// (String) ID of the Encryption key to use for data encryption. Must be an ARN for AWS services or a Key Resource Path for GCP services.
	// ID of the Encryption key to use for data encryption. Must be an ARN for AWS services or a Key Resource Path for GCP services.
	// +kubebuilder:validation:Optional
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`
}

// TransparentDataEncryptionKeyAssociationSpec defines the desired state of TransparentDataEncryptionKeyAssociation
type TransparentDataEncryptionKeyAssociationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TransparentDataEncryptionKeyAssociationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TransparentDataEncryptionKeyAssociationInitParameters `json:"initProvider,omitempty"`
}

// TransparentDataEncryptionKeyAssociationStatus defines the observed state of TransparentDataEncryptionKeyAssociation.
type TransparentDataEncryptionKeyAssociationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TransparentDataEncryptionKeyAssociationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TransparentDataEncryptionKeyAssociation is the Schema for the TransparentDataEncryptionKeyAssociations API. You can use the clickhouse_service_transparent_data_encryption_key_association resource to associate your own Encryption Key with a Clickhouse Service with the Transparent Data Encryption (TDE) feature enabled. Please note that this feature requires an organization with the Enterprise plan.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,clickhouse}
type TransparentDataEncryptionKeyAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.keyId) || (has(self.initProvider) && has(self.initProvider.keyId))",message="spec.forProvider.keyId is a required parameter"
	Spec   TransparentDataEncryptionKeyAssociationSpec   `json:"spec"`
	Status TransparentDataEncryptionKeyAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TransparentDataEncryptionKeyAssociationList contains a list of TransparentDataEncryptionKeyAssociations
type TransparentDataEncryptionKeyAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TransparentDataEncryptionKeyAssociation `json:"items"`
}

// Repository type metadata.
var (
	TransparentDataEncryptionKeyAssociation_Kind             = "TransparentDataEncryptionKeyAssociation"
	TransparentDataEncryptionKeyAssociation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TransparentDataEncryptionKeyAssociation_Kind}.String()
	TransparentDataEncryptionKeyAssociation_KindAPIVersion   = TransparentDataEncryptionKeyAssociation_Kind + "." + CRDGroupVersion.String()
	TransparentDataEncryptionKeyAssociation_GroupVersionKind = CRDGroupVersion.WithKind(TransparentDataEncryptionKeyAssociation_Kind)
)

func init() {
	SchemeBuilder.Register(&TransparentDataEncryptionKeyAssociation{}, &TransparentDataEncryptionKeyAssociationList{})
}
