// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type UpgradeWindowInitParameters struct {

	// : one of 0, 6, 12, 18
	// UTC hour when the upgrade window starts. Must be one of 0, 6, 12, or 18.
	StartHourUtc *float64 `json:"startHourUtc,omitempty" tf:"start_hour_utc,omitempty"`

	// : 0 (Sunday) – 6 (Saturday)
	// Day of the week the upgrade window starts. 0 = Sunday, 1 = Monday, …, 6 = Saturday.
	Weekday *float64 `json:"weekday,omitempty" tf:"weekday,omitempty"`
}

type UpgradeWindowObservation struct {

	// controlled; currently always 6.
	// Length of the upgrade window in hours. Server-controlled; currently always 6.
	Duration *float64 `json:"duration,omitempty" tf:"duration,omitempty"`

	// (String) Resource identifier. Equal to service_id (one window per service).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// : one of 0, 6, 12, 18
	// UTC hour when the upgrade window starts. Must be one of 0, 6, 12, or 18.
	StartHourUtc *float64 `json:"startHourUtc,omitempty" tf:"start_hour_utc,omitempty"`

	// : 0 (Sunday) – 6 (Saturday)
	// Day of the week the upgrade window starts. 0 = Sunday, 1 = Monday, …, 6 = Saturday.
	Weekday *float64 `json:"weekday,omitempty" tf:"weekday,omitempty"`
}

type UpgradeWindowParameters struct {

	// : one of 0, 6, 12, 18
	// UTC hour when the upgrade window starts. Must be one of 0, 6, 12, or 18.
	// +kubebuilder:validation:Optional
	StartHourUtc *float64 `json:"startHourUtc,omitempty" tf:"start_hour_utc,omitempty"`

	// : 0 (Sunday) – 6 (Saturday)
	// Day of the week the upgrade window starts. 0 = Sunday, 1 = Monday, …, 6 = Saturday.
	// +kubebuilder:validation:Optional
	Weekday *float64 `json:"weekday,omitempty" tf:"weekday,omitempty"`
}

// UpgradeWindowSpec defines the desired state of UpgradeWindow
type UpgradeWindowSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UpgradeWindowParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UpgradeWindowInitParameters `json:"initProvider,omitempty"`
}

// UpgradeWindowStatus defines the observed state of UpgradeWindow.
type UpgradeWindowStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               UpgradeWindowObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UpgradeWindow is the Schema for the UpgradeWindows API. You can use the clickhouse_service_upgrade_window resource to pin the weekly upgrade window for a ClickHouse Cloud service. When configured, the data plane only attempts service upgrades during the declared window. The window is a single weekly recurrence: a weekday plus a start_hour_utc. The window currently lasts 6 hours from start_hour_utc; duration is returned by the API and exposed as a read-only attribute. ~> Note: This resource is in beta. Setting or updating an upgrade window requires the canUseScheduledUpgrades entitlement — reach out to ClickHouse support if the API returns 403 FORBIDDEN. Deleting an upgrade window is allowed even after the entitlement is lost, so existing windows can always be cleared. Primary services only The upgrade window can only be set on primary services. Secondary services inherit the window from their primary. Applying this resource against a secondary service returns a 400 with the message cannot set upgrade window on a secondary service, surfaced by the provider as Upgrade windows can only be set on primary services. Allowed values weekday: 0 (Sunday) – 6 (Saturday)start_hour_utc: one of 0, 6, 12, 18 Best-effort overwrite protection Create performs a GET before issuing the PUT so that an existing window (e.g. one configured out-of-band) surfaces a "please import" diagnostic instead of being silently overwritten. The check is best-effort: a window created between this resource's GET and PUT (e.g. Import
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,clickhouse}
type UpgradeWindow struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.startHourUtc) || (has(self.initProvider) && has(self.initProvider.startHourUtc))",message="spec.forProvider.startHourUtc is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.weekday) || (has(self.initProvider) && has(self.initProvider.weekday))",message="spec.forProvider.weekday is a required parameter"
	Spec   UpgradeWindowSpec   `json:"spec"`
	Status UpgradeWindowStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UpgradeWindowList contains a list of UpgradeWindows
type UpgradeWindowList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UpgradeWindow `json:"items"`
}

// Repository type metadata.
var (
	UpgradeWindow_Kind             = "UpgradeWindow"
	UpgradeWindow_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UpgradeWindow_Kind}.String()
	UpgradeWindow_KindAPIVersion   = UpgradeWindow_Kind + "." + CRDGroupVersion.String()
	UpgradeWindow_GroupVersionKind = CRDGroupVersion.WithKind(UpgradeWindow_Kind)
)

func init() {
	SchemeBuilder.Register(&UpgradeWindow{}, &UpgradeWindowList{})
}
