//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingInitParameters) DeepCopyInto(out *MappingInitParameters) {
	*out = *in
	if in.PrivateDNSName != nil {
		in, out := &in.PrivateDNSName, &out.PrivateDNSName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingInitParameters.
func (in *MappingInitParameters) DeepCopy() *MappingInitParameters {
	if in == nil {
		return nil
	}
	out := new(MappingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingObservation) DeepCopyInto(out *MappingObservation) {
	*out = *in
	if in.PrivateDNSName != nil {
		in, out := &in.PrivateDNSName, &out.PrivateDNSName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingObservation.
func (in *MappingObservation) DeepCopy() *MappingObservation {
	if in == nil {
		return nil
	}
	out := new(MappingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingParameters) DeepCopyInto(out *MappingParameters) {
	*out = *in
	if in.PrivateDNSName != nil {
		in, out := &in.PrivateDNSName, &out.PrivateDNSName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingParameters.
func (in *MappingParameters) DeepCopy() *MappingParameters {
	if in == nil {
		return nil
	}
	out := new(MappingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpoint) DeepCopyInto(out *ReversePrivateEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpoint.
func (in *ReversePrivateEndpoint) DeepCopy() *ReversePrivateEndpoint {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReversePrivateEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpointCustomPrivateDNS) DeepCopyInto(out *ReversePrivateEndpointCustomPrivateDNS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpointCustomPrivateDNS.
func (in *ReversePrivateEndpointCustomPrivateDNS) DeepCopy() *ReversePrivateEndpointCustomPrivateDNS {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpointCustomPrivateDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReversePrivateEndpointCustomPrivateDNS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpointCustomPrivateDNSInitParameters) DeepCopyInto(out *ReversePrivateEndpointCustomPrivateDNSInitParameters) {
	*out = *in
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = make([]MappingInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReversePrivateEndpointID != nil {
		in, out := &in.ReversePrivateEndpointID, &out.ReversePrivateEndpointID
		*out = new(string)
		**out = **in
	}
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpointCustomPrivateDNSInitParameters.
func (in *ReversePrivateEndpointCustomPrivateDNSInitParameters) DeepCopy() *ReversePrivateEndpointCustomPrivateDNSInitParameters {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpointCustomPrivateDNSInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpointCustomPrivateDNSList) DeepCopyInto(out *ReversePrivateEndpointCustomPrivateDNSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReversePrivateEndpointCustomPrivateDNS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpointCustomPrivateDNSList.
func (in *ReversePrivateEndpointCustomPrivateDNSList) DeepCopy() *ReversePrivateEndpointCustomPrivateDNSList {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpointCustomPrivateDNSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReversePrivateEndpointCustomPrivateDNSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpointCustomPrivateDNSObservation) DeepCopyInto(out *ReversePrivateEndpointCustomPrivateDNSObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = make([]MappingObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReversePrivateEndpointID != nil {
		in, out := &in.ReversePrivateEndpointID, &out.ReversePrivateEndpointID
		*out = new(string)
		**out = **in
	}
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpointCustomPrivateDNSObservation.
func (in *ReversePrivateEndpointCustomPrivateDNSObservation) DeepCopy() *ReversePrivateEndpointCustomPrivateDNSObservation {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpointCustomPrivateDNSObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpointCustomPrivateDNSParameters) DeepCopyInto(out *ReversePrivateEndpointCustomPrivateDNSParameters) {
	*out = *in
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = make([]MappingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReversePrivateEndpointID != nil {
		in, out := &in.ReversePrivateEndpointID, &out.ReversePrivateEndpointID
		*out = new(string)
		**out = **in
	}
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpointCustomPrivateDNSParameters.
func (in *ReversePrivateEndpointCustomPrivateDNSParameters) DeepCopy() *ReversePrivateEndpointCustomPrivateDNSParameters {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpointCustomPrivateDNSParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpointCustomPrivateDNSSpec) DeepCopyInto(out *ReversePrivateEndpointCustomPrivateDNSSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpointCustomPrivateDNSSpec.
func (in *ReversePrivateEndpointCustomPrivateDNSSpec) DeepCopy() *ReversePrivateEndpointCustomPrivateDNSSpec {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpointCustomPrivateDNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpointCustomPrivateDNSStatus) DeepCopyInto(out *ReversePrivateEndpointCustomPrivateDNSStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpointCustomPrivateDNSStatus.
func (in *ReversePrivateEndpointCustomPrivateDNSStatus) DeepCopy() *ReversePrivateEndpointCustomPrivateDNSStatus {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpointCustomPrivateDNSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpointInitParameters) DeepCopyInto(out *ReversePrivateEndpointInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GCPServiceAttachment != nil {
		in, out := &in.GCPServiceAttachment, &out.GCPServiceAttachment
		*out = new(string)
		**out = **in
	}
	if in.MskAuthentication != nil {
		in, out := &in.MskAuthentication, &out.MskAuthentication
		*out = new(string)
		**out = **in
	}
	if in.MskClusterArn != nil {
		in, out := &in.MskClusterArn, &out.MskClusterArn
		*out = new(string)
		**out = **in
	}
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.VPCEndpointServiceName != nil {
		in, out := &in.VPCEndpointServiceName, &out.VPCEndpointServiceName
		*out = new(string)
		**out = **in
	}
	if in.VPCResourceConfigurationID != nil {
		in, out := &in.VPCResourceConfigurationID, &out.VPCResourceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.VPCResourceShareArn != nil {
		in, out := &in.VPCResourceShareArn, &out.VPCResourceShareArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpointInitParameters.
func (in *ReversePrivateEndpointInitParameters) DeepCopy() *ReversePrivateEndpointInitParameters {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpointInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpointList) DeepCopyInto(out *ReversePrivateEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReversePrivateEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpointList.
func (in *ReversePrivateEndpointList) DeepCopy() *ReversePrivateEndpointList {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReversePrivateEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpointObservation) DeepCopyInto(out *ReversePrivateEndpointObservation) {
	*out = *in
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EndpointID != nil {
		in, out := &in.EndpointID, &out.EndpointID
		*out = new(string)
		**out = **in
	}
	if in.GCPServiceAttachment != nil {
		in, out := &in.GCPServiceAttachment, &out.GCPServiceAttachment
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MskAuthentication != nil {
		in, out := &in.MskAuthentication, &out.MskAuthentication
		*out = new(string)
		**out = **in
	}
	if in.MskClusterArn != nil {
		in, out := &in.MskClusterArn, &out.MskClusterArn
		*out = new(string)
		**out = **in
	}
	if in.PrivateDNSNames != nil {
		in, out := &in.PrivateDNSNames, &out.PrivateDNSNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.VPCEndpointServiceName != nil {
		in, out := &in.VPCEndpointServiceName, &out.VPCEndpointServiceName
		*out = new(string)
		**out = **in
	}
	if in.VPCResourceConfigurationID != nil {
		in, out := &in.VPCResourceConfigurationID, &out.VPCResourceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.VPCResourceShareArn != nil {
		in, out := &in.VPCResourceShareArn, &out.VPCResourceShareArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpointObservation.
func (in *ReversePrivateEndpointObservation) DeepCopy() *ReversePrivateEndpointObservation {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpointObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpointParameters) DeepCopyInto(out *ReversePrivateEndpointParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GCPServiceAttachment != nil {
		in, out := &in.GCPServiceAttachment, &out.GCPServiceAttachment
		*out = new(string)
		**out = **in
	}
	if in.MskAuthentication != nil {
		in, out := &in.MskAuthentication, &out.MskAuthentication
		*out = new(string)
		**out = **in
	}
	if in.MskClusterArn != nil {
		in, out := &in.MskClusterArn, &out.MskClusterArn
		*out = new(string)
		**out = **in
	}
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.VPCEndpointServiceName != nil {
		in, out := &in.VPCEndpointServiceName, &out.VPCEndpointServiceName
		*out = new(string)
		**out = **in
	}
	if in.VPCResourceConfigurationID != nil {
		in, out := &in.VPCResourceConfigurationID, &out.VPCResourceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.VPCResourceShareArn != nil {
		in, out := &in.VPCResourceShareArn, &out.VPCResourceShareArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpointParameters.
func (in *ReversePrivateEndpointParameters) DeepCopy() *ReversePrivateEndpointParameters {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpointParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpointSpec) DeepCopyInto(out *ReversePrivateEndpointSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpointSpec.
func (in *ReversePrivateEndpointSpec) DeepCopy() *ReversePrivateEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversePrivateEndpointStatus) DeepCopyInto(out *ReversePrivateEndpointStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversePrivateEndpointStatus.
func (in *ReversePrivateEndpointStatus) DeepCopy() *ReversePrivateEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(ReversePrivateEndpointStatus)
	in.DeepCopyInto(out)
	return out
}
