// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ReversePrivateEndpointInitParameters struct {

	// (String) Description of the reverse private endpoint
	// Description of the reverse private endpoint
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) GCP PSC service attachment URI, required for GCP_PSC_SERVICE_ATTACHMENT type. Format: projects/{project}/regions/{region}/serviceAttachments/{name}
	// GCP PSC service attachment URI, required for GCP_PSC_SERVICE_ATTACHMENT type. Format: projects/{project}/regions/{region}/serviceAttachments/{name}
	GCPServiceAttachment *string `json:"gcpServiceAttachment,omitempty" tf:"gcp_service_attachment,omitempty"`

	// (String) MSK cluster authentication type (SASL_IAM or SASL_SCRAM), required for MSK_MULTI_VPC type
	// MSK cluster authentication type (SASL_IAM or SASL_SCRAM), required for MSK_MULTI_VPC type
	MskAuthentication *string `json:"mskAuthentication,omitempty" tf:"msk_authentication,omitempty"`

	// (String) MSK cluster ARN, required for MSK_MULTI_VPC type
	// MSK cluster ARN, required for MSK_MULTI_VPC type
	MskClusterArn *string `json:"mskClusterArn,omitempty" tf:"msk_cluster_arn,omitempty"`

	// (String) The ID of the ClickHouse service to associate with this reverse private endpoint
	// The ID of the ClickHouse service to associate with this reverse private endpoint
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/namespaced/clickhouse/v1alpha1.Service
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// Reference to a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDRef *v1.NamespacedReference `json:"serviceIdRef,omitempty" tf:"-"`

	// Selector for a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDSelector *v1.NamespacedSelector `json:"serviceIdSelector,omitempty" tf:"-"`

	// (String) Type of the reverse private endpoint (VPC_ENDPOINT_SERVICE, VPC_RESOURCE, MSK_MULTI_VPC, or GCP_PSC_SERVICE_ATTACHMENT)
	// Type of the reverse private endpoint (VPC_ENDPOINT_SERVICE, VPC_RESOURCE, MSK_MULTI_VPC, or GCP_PSC_SERVICE_ATTACHMENT)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) VPC endpoint service name, required for VPC_ENDPOINT_SERVICE type
	// VPC endpoint service name, required for VPC_ENDPOINT_SERVICE type
	VPCEndpointServiceName *string `json:"vpcEndpointServiceName,omitempty" tf:"vpc_endpoint_service_name,omitempty"`

	// (String) VPC resource configuration ID, required for VPC_RESOURCE type
	// VPC resource configuration ID, required for VPC_RESOURCE type
	VPCResourceConfigurationID *string `json:"vpcResourceConfigurationId,omitempty" tf:"vpc_resource_configuration_id,omitempty"`

	// (String) VPC resource share ARN, required for VPC_RESOURCE type
	// VPC resource share ARN, required for VPC_RESOURCE type
	VPCResourceShareArn *string `json:"vpcResourceShareArn,omitempty" tf:"vpc_resource_share_arn,omitempty"`
}

type ReversePrivateEndpointObservation struct {

	// (List of String) Reverse private endpoint internal DNS names
	// Reverse private endpoint internal DNS names
	DNSNames []*string `json:"dnsNames,omitempty" tf:"dns_names,omitempty"`

	// (String) Description of the reverse private endpoint
	// Description of the reverse private endpoint
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Reverse private endpoint endpoint ID
	// Reverse private endpoint endpoint ID
	EndpointID *string `json:"endpointId,omitempty" tf:"endpoint_id,omitempty"`

	// (String) GCP PSC service attachment URI, required for GCP_PSC_SERVICE_ATTACHMENT type. Format: projects/{project}/regions/{region}/serviceAttachments/{name}
	// GCP PSC service attachment URI, required for GCP_PSC_SERVICE_ATTACHMENT type. Format: projects/{project}/regions/{region}/serviceAttachments/{name}
	GCPServiceAttachment *string `json:"gcpServiceAttachment,omitempty" tf:"gcp_service_attachment,omitempty"`

	// (String) Unique identifier for the reverse private endpoint
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) MSK cluster authentication type (SASL_IAM or SASL_SCRAM), required for MSK_MULTI_VPC type
	// MSK cluster authentication type (SASL_IAM or SASL_SCRAM), required for MSK_MULTI_VPC type
	MskAuthentication *string `json:"mskAuthentication,omitempty" tf:"msk_authentication,omitempty"`

	// (String) MSK cluster ARN, required for MSK_MULTI_VPC type
	// MSK cluster ARN, required for MSK_MULTI_VPC type
	MskClusterArn *string `json:"mskClusterArn,omitempty" tf:"msk_cluster_arn,omitempty"`

	// (List of String) Reverse private endpoint private DNS names
	// Reverse private endpoint private DNS names
	PrivateDNSNames []*string `json:"privateDnsNames,omitempty" tf:"private_dns_names,omitempty"`

	// (String) The ID of the ClickHouse service to associate with this reverse private endpoint
	// The ID of the ClickHouse service to associate with this reverse private endpoint
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) Status of the reverse private endpoint
	// Status of the reverse private endpoint
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Type of the reverse private endpoint (VPC_ENDPOINT_SERVICE, VPC_RESOURCE, MSK_MULTI_VPC, or GCP_PSC_SERVICE_ATTACHMENT)
	// Type of the reverse private endpoint (VPC_ENDPOINT_SERVICE, VPC_RESOURCE, MSK_MULTI_VPC, or GCP_PSC_SERVICE_ATTACHMENT)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) VPC endpoint service name, required for VPC_ENDPOINT_SERVICE type
	// VPC endpoint service name, required for VPC_ENDPOINT_SERVICE type
	VPCEndpointServiceName *string `json:"vpcEndpointServiceName,omitempty" tf:"vpc_endpoint_service_name,omitempty"`

	// (String) VPC resource configuration ID, required for VPC_RESOURCE type
	// VPC resource configuration ID, required for VPC_RESOURCE type
	VPCResourceConfigurationID *string `json:"vpcResourceConfigurationId,omitempty" tf:"vpc_resource_configuration_id,omitempty"`

	// (String) VPC resource share ARN, required for VPC_RESOURCE type
	// VPC resource share ARN, required for VPC_RESOURCE type
	VPCResourceShareArn *string `json:"vpcResourceShareArn,omitempty" tf:"vpc_resource_share_arn,omitempty"`
}

type ReversePrivateEndpointParameters struct {

	// (String) Description of the reverse private endpoint
	// Description of the reverse private endpoint
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) GCP PSC service attachment URI, required for GCP_PSC_SERVICE_ATTACHMENT type. Format: projects/{project}/regions/{region}/serviceAttachments/{name}
	// GCP PSC service attachment URI, required for GCP_PSC_SERVICE_ATTACHMENT type. Format: projects/{project}/regions/{region}/serviceAttachments/{name}
	// +kubebuilder:validation:Optional
	GCPServiceAttachment *string `json:"gcpServiceAttachment,omitempty" tf:"gcp_service_attachment,omitempty"`

	// (String) MSK cluster authentication type (SASL_IAM or SASL_SCRAM), required for MSK_MULTI_VPC type
	// MSK cluster authentication type (SASL_IAM or SASL_SCRAM), required for MSK_MULTI_VPC type
	// +kubebuilder:validation:Optional
	MskAuthentication *string `json:"mskAuthentication,omitempty" tf:"msk_authentication,omitempty"`

	// (String) MSK cluster ARN, required for MSK_MULTI_VPC type
	// MSK cluster ARN, required for MSK_MULTI_VPC type
	// +kubebuilder:validation:Optional
	MskClusterArn *string `json:"mskClusterArn,omitempty" tf:"msk_cluster_arn,omitempty"`

	// (String) The ID of the ClickHouse service to associate with this reverse private endpoint
	// The ID of the ClickHouse service to associate with this reverse private endpoint
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/namespaced/clickhouse/v1alpha1.Service
	// +kubebuilder:validation:Optional
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// Reference to a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDRef *v1.NamespacedReference `json:"serviceIdRef,omitempty" tf:"-"`

	// Selector for a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDSelector *v1.NamespacedSelector `json:"serviceIdSelector,omitempty" tf:"-"`

	// (String) Type of the reverse private endpoint (VPC_ENDPOINT_SERVICE, VPC_RESOURCE, MSK_MULTI_VPC, or GCP_PSC_SERVICE_ATTACHMENT)
	// Type of the reverse private endpoint (VPC_ENDPOINT_SERVICE, VPC_RESOURCE, MSK_MULTI_VPC, or GCP_PSC_SERVICE_ATTACHMENT)
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) VPC endpoint service name, required for VPC_ENDPOINT_SERVICE type
	// VPC endpoint service name, required for VPC_ENDPOINT_SERVICE type
	// +kubebuilder:validation:Optional
	VPCEndpointServiceName *string `json:"vpcEndpointServiceName,omitempty" tf:"vpc_endpoint_service_name,omitempty"`

	// (String) VPC resource configuration ID, required for VPC_RESOURCE type
	// VPC resource configuration ID, required for VPC_RESOURCE type
	// +kubebuilder:validation:Optional
	VPCResourceConfigurationID *string `json:"vpcResourceConfigurationId,omitempty" tf:"vpc_resource_configuration_id,omitempty"`

	// (String) VPC resource share ARN, required for VPC_RESOURCE type
	// VPC resource share ARN, required for VPC_RESOURCE type
	// +kubebuilder:validation:Optional
	VPCResourceShareArn *string `json:"vpcResourceShareArn,omitempty" tf:"vpc_resource_share_arn,omitempty"`
}

// ReversePrivateEndpointSpec defines the desired state of ReversePrivateEndpoint
type ReversePrivateEndpointSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ReversePrivateEndpointParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ReversePrivateEndpointInitParameters `json:"initProvider,omitempty"`
}

// ReversePrivateEndpointStatus defines the observed state of ReversePrivateEndpoint.
type ReversePrivateEndpointStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ReversePrivateEndpointObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ReversePrivateEndpoint is the Schema for the ReversePrivateEndpoints API. You can use the clickhouse_clickpipes_reverse_private_endpoint resource to create and manage reverse private endpoints for secure ClickPipes data source connections in ClickHouse Cloud. Supported endpoint types: VPC_ENDPOINT_SERVICE, VPC_RESOURCE, MSK_MULTI_VPC, and GCP_PSC_SERVICE_ATTACHMENT. ~> Note: All fields on this resource are immutable after creation. Any change will force replacement (destroy and recreate). Use clickhouse_clickpipes_reverse_private_endpoint_custom_private_dns to manage custom private DNS mappings for a reverse private endpoint.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,clickhouse}
type ReversePrivateEndpoint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ReversePrivateEndpointSpec   `json:"spec"`
	Status ReversePrivateEndpointStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ReversePrivateEndpointList contains a list of ReversePrivateEndpoints
type ReversePrivateEndpointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReversePrivateEndpoint `json:"items"`
}

// Repository type metadata.
var (
	ReversePrivateEndpoint_Kind             = "ReversePrivateEndpoint"
	ReversePrivateEndpoint_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ReversePrivateEndpoint_Kind}.String()
	ReversePrivateEndpoint_KindAPIVersion   = ReversePrivateEndpoint_Kind + "." + CRDGroupVersion.String()
	ReversePrivateEndpoint_GroupVersionKind = CRDGroupVersion.WithKind(ReversePrivateEndpoint_Kind)
)

func init() {
	SchemeBuilder.Register(&ReversePrivateEndpoint{}, &ReversePrivateEndpointList{})
}
