// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SSHKeyInitParameters struct {

	// (String) Description of the SSH key resource, at most 255 characters. Immutable; changing it forces resource replacement (the public API has no update operation for SSH key resources).
	// Description of the SSH key resource, at most 255 characters. Immutable; changing it forces resource replacement (the public API has no update operation for SSH key resources).
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Hostname or IP address of the SSH bastion. Immutable; changing it forces resource replacement.
	// Hostname or IP address of the SSH bastion. Immutable; changing it forces resource replacement.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String) Name of the SSH key resource. Unique per service and immutable; changing it forces resource replacement.
	// Name of the SSH key resource. Unique per service and immutable; changing it forces resource replacement.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Port of the SSH bastion. Defaults to 22. Immutable; changing it forces resource replacement.
	// Port of the SSH bastion. Defaults to 22. Immutable; changing it forces resource replacement.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) The ID of the ClickHouse service this SSH key resource belongs to
	// The ID of the ClickHouse service this SSH key resource belongs to
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/namespaced/clickhouse/v1alpha1.Service
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// Reference to a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDRef *v2.NamespacedReference `json:"serviceIdRef,omitempty" tf:"-"`

	// Selector for a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDSelector *v2.NamespacedSelector `json:"serviceIdSelector,omitempty" tf:"-"`

	// (String) Username to authenticate with on the SSH bastion. Immutable; changing it forces resource replacement.
	// Username to authenticate with on the SSH bastion. Immutable; changing it forces resource replacement.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SSHKeyObservation struct {

	// (String) Timestamp when the SSH key resource was created.
	// Timestamp when the SSH key resource was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Description of the SSH key resource, at most 255 characters. Immutable; changing it forces resource replacement (the public API has no update operation for SSH key resources).
	// Description of the SSH key resource, at most 255 characters. Immutable; changing it forces resource replacement (the public API has no update operation for SSH key resources).
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Hostname or IP address of the SSH bastion. Immutable; changing it forces resource replacement.
	// Hostname or IP address of the SSH bastion. Immutable; changing it forces resource replacement.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String) Unique identifier for the SSH key resource
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Timestamp of the last connectivity validation, if any.
	// Timestamp of the last connectivity validation, if any.
	LastValidatedAt *string `json:"lastValidatedAt,omitempty" tf:"last_validated_at,omitempty"`

	// (String) Name of the SSH key resource. Unique per service and immutable; changing it forces resource replacement.
	// Name of the SSH key resource. Unique per service and immutable; changing it forces resource replacement.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Port of the SSH bastion. Defaults to 22. Immutable; changing it forces resource replacement.
	// Port of the SSH bastion. Defaults to 22. Immutable; changing it forces resource replacement.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) The OpenSSH public key generated by the server. Install this in the bastion's authorized_keys before validating connectivity.
	// The OpenSSH public key generated by the server. Install this in the bastion's `authorized_keys` before validating connectivity.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// (String) The ID of the ClickHouse service this SSH key resource belongs to
	// The ID of the ClickHouse service this SSH key resource belongs to
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) Validation lifecycle status of the SSH key resource (pending, active, or failed).
	// Validation lifecycle status of the SSH key resource (pending, active, or failed).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// readable detail about the current status, e.g. the reason a validation failed.
	// Human-readable detail about the current status, e.g. the reason a validation failed.
	StatusMessage *string `json:"statusMessage,omitempty" tf:"status_message,omitempty"`

	// (String) Timestamp when the SSH key resource was last updated.
	// Timestamp when the SSH key resource was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (String) Username to authenticate with on the SSH bastion. Immutable; changing it forces resource replacement.
	// Username to authenticate with on the SSH bastion. Immutable; changing it forces resource replacement.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SSHKeyParameters struct {

	// (String) Description of the SSH key resource, at most 255 characters. Immutable; changing it forces resource replacement (the public API has no update operation for SSH key resources).
	// Description of the SSH key resource, at most 255 characters. Immutable; changing it forces resource replacement (the public API has no update operation for SSH key resources).
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Hostname or IP address of the SSH bastion. Immutable; changing it forces resource replacement.
	// Hostname or IP address of the SSH bastion. Immutable; changing it forces resource replacement.
	// +kubebuilder:validation:Optional
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String) Name of the SSH key resource. Unique per service and immutable; changing it forces resource replacement.
	// Name of the SSH key resource. Unique per service and immutable; changing it forces resource replacement.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Port of the SSH bastion. Defaults to 22. Immutable; changing it forces resource replacement.
	// Port of the SSH bastion. Defaults to 22. Immutable; changing it forces resource replacement.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) The ID of the ClickHouse service this SSH key resource belongs to
	// The ID of the ClickHouse service this SSH key resource belongs to
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/namespaced/clickhouse/v1alpha1.Service
	// +kubebuilder:validation:Optional
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// Reference to a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDRef *v2.NamespacedReference `json:"serviceIdRef,omitempty" tf:"-"`

	// Selector for a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDSelector *v2.NamespacedSelector `json:"serviceIdSelector,omitempty" tf:"-"`

	// (String) Username to authenticate with on the SSH bastion. Immutable; changing it forces resource replacement.
	// Username to authenticate with on the SSH bastion. Immutable; changing it forces resource replacement.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// SSHKeySpec defines the desired state of SSHKey
type SSHKeySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SSHKeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SSHKeyInitParameters `json:"initProvider,omitempty"`
}

// SSHKeyStatus defines the observed state of SSHKey.
type SSHKeyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SSHKeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SSHKey is the Schema for the SSHKeys API. You can use the clickhouse_clickpipes_ssh_key resource to create a standalone, service-scoped SSH key resource for ClickPipes. The server generates an Ed25519 keypair and returns the OpenSSH public_key. Install that public key in your bastion's authorized_keys so that ClickPipes can tunnel through it. The private key never leaves ClickHouse Cloud. Once created, reference the resource from a ClickPipe source via its ssh_key_resource_id attribute (supported on Kafka, Postgres, MySQL, and MongoDB sources) instead of providing inline SSH configuration. A reference is mutually exclusive with inline SSH config and is immutable on the pipe; changing it forces the pipe to be recreated. The resource lifecycle is: pending — created, connectivity not yet validated.active — the last connectivity validation succeeded.failed — the last connectivity validation failed. All attributes (name, description, host, port, username) are immutable; changing any of them forces resource replacement — the public API exposes no update operation for SSH key resources. ~> Note: Connectivity validation requires the public key to already be installed on the bastion, so it is a day-2 operation performed out of band and is not run automatically when the resource is created.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,clickhouse}
type SSHKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.host) || (has(self.initProvider) && has(self.initProvider.host))",message="spec.forProvider.host is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   SSHKeySpec   `json:"spec"`
	Status SSHKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SSHKeyList contains a list of SSHKeys
type SSHKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SSHKey `json:"items"`
}

// Repository type metadata.
var (
	SSHKey_Kind             = "SSHKey"
	SSHKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SSHKey_Kind}.String()
	SSHKey_KindAPIVersion   = SSHKey_Kind + "." + CRDGroupVersion.String()
	SSHKey_GroupVersionKind = CRDGroupVersion.WithKind(SSHKey_Kind)
)

func init() {
	SchemeBuilder.Register(&SSHKey{}, &SSHKeyList{})
}
