apiVersion: clickstack.clickhouse.m.crossplane.io/v1alpha1
kind: Connection
metadata:
  annotations:
    meta.upbound.io/example-id: clickstack/v1alpha1/connection
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: crossplane-system
spec:
  forProvider:
    host: https://clickhouse.example.com:8443
    name: Production ClickHouse
    passwordSecretRef:
      key: example-key
      name: example-secret
    username: default

---

apiVersion: clickstack.clickhouse.m.crossplane.io/v1alpha1
kind: Source
metadata:
  annotations:
    meta.upbound.io/example-id: clickstack/v1alpha1/connection
  labels:
    testing.upbound.io/example-name: logs
  name: logs
  namespace: crossplane-system
spec:
  forProvider:
    connectionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    from:
      databaseName: otel
      tableName: otel_logs
    kind: log
    name: Logs
    timestampValueExpression: Timestamp
