apiVersion: clickstack.clickhouse.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: clickstack/v1alpha1/role
  labels:
    testing.upbound.io/example-name: analyst
  name: analyst
spec:
  forProvider:
    description: Read-only access to dashboards and searches
    name: Analyst
    permissions:
    - action: read
      subject: Dashboard
    - action: read
      subject: SavedSearch
