// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type BackupConfigurationInitParameters struct {

	// (Number) Interval in hours between each backup.
	// Interval in hours between each backup.
	BackupPeriodInHours *float64 `json:"backupPeriodInHours,omitempty" tf:"backup_period_in_hours,omitempty"`

	// (Number) How long in hours to keep a backup before deleting it.
	// How long in hours to keep a backup before deleting it.
	BackupRetentionPeriodInHours *float64 `json:"backupRetentionPeriodInHours,omitempty" tf:"backup_retention_period_in_hours,omitempty"`

	// (String) Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup_period_in_hours must be null and backups are created once a day.
	// Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup_period_in_hours must be null and backups are created once a day.
	BackupStartTime *string `json:"backupStartTime,omitempty" tf:"backup_start_time,omitempty"`
}

type BackupConfigurationObservation struct {

	// (Number) Interval in hours between each backup.
	// Interval in hours between each backup.
	BackupPeriodInHours *float64 `json:"backupPeriodInHours,omitempty" tf:"backup_period_in_hours,omitempty"`

	// (Number) How long in hours to keep a backup before deleting it.
	// How long in hours to keep a backup before deleting it.
	BackupRetentionPeriodInHours *float64 `json:"backupRetentionPeriodInHours,omitempty" tf:"backup_retention_period_in_hours,omitempty"`

	// (String) Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup_period_in_hours must be null and backups are created once a day.
	// Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup_period_in_hours must be null and backups are created once a day.
	BackupStartTime *string `json:"backupStartTime,omitempty" tf:"backup_start_time,omitempty"`
}

type BackupConfigurationParameters struct {

	// (Number) Interval in hours between each backup.
	// Interval in hours between each backup.
	// +kubebuilder:validation:Optional
	BackupPeriodInHours *float64 `json:"backupPeriodInHours,omitempty" tf:"backup_period_in_hours,omitempty"`

	// (Number) How long in hours to keep a backup before deleting it.
	// How long in hours to keep a backup before deleting it.
	// +kubebuilder:validation:Optional
	BackupRetentionPeriodInHours *float64 `json:"backupRetentionPeriodInHours,omitempty" tf:"backup_retention_period_in_hours,omitempty"`

	// (String) Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup_period_in_hours must be null and backups are created once a day.
	// Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup_period_in_hours must be null and backups are created once a day.
	// +kubebuilder:validation:Optional
	BackupStartTime *string `json:"backupStartTime,omitempty" tf:"backup_start_time,omitempty"`
}

type EndpointsInitParameters struct {

	// (Attributes) (see below for nested schema)
	HTTPS *HTTPSInitParameters `json:"https,omitempty" tf:"https,omitempty"`

	// (Attributes) (see below for nested schema)
	MySQL *EndpointsMySQLInitParameters `json:"mysql,omitempty" tf:"mysql,omitempty"`

	// (Attributes) (see below for nested schema)
	Nativesecure *NativesecureInitParameters `json:"nativesecure,omitempty" tf:"nativesecure,omitempty"`
}

type EndpointsMySQLInitParameters struct {

	// (Boolean) Wether to enable the mysql endpoint or not.
	// Wether to enable the mysql endpoint or not.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type EndpointsMySQLObservation struct {

	// (Boolean) Wether to enable the mysql endpoint or not.
	// Wether to enable the mysql endpoint or not.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Endpoint host.
	// Endpoint host.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (Number) Endpoint port.
	// Endpoint port.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type EndpointsMySQLParameters struct {

	// (Boolean) Wether to enable the mysql endpoint or not.
	// Wether to enable the mysql endpoint or not.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`
}

type EndpointsObservation struct {

	// (Attributes) (see below for nested schema)
	HTTPS *HTTPSObservation `json:"https,omitempty" tf:"https,omitempty"`

	// (Attributes) (see below for nested schema)
	MySQL *EndpointsMySQLObservation `json:"mysql,omitempty" tf:"mysql,omitempty"`

	// (Attributes) (see below for nested schema)
	Nativesecure *NativesecureObservation `json:"nativesecure,omitempty" tf:"nativesecure,omitempty"`
}

type EndpointsParameters struct {

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	HTTPS *HTTPSParameters `json:"https,omitempty" tf:"https,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	MySQL *EndpointsMySQLParameters `json:"mysql,omitempty" tf:"mysql,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Nativesecure *NativesecureParameters `json:"nativesecure,omitempty" tf:"nativesecure,omitempty"`
}

type HTTPSInitParameters struct {
}

type HTTPSObservation struct {

	// (String) Endpoint host.
	// Endpoint host.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (Number) Endpoint port.
	// Endpoint port.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type HTTPSParameters struct {
}

type IPAccessInitParameters struct {

	// (String) Description of the IP address.
	// Description of the IP address.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) IP address allowed to access the service. In case you want to set the ip_access to anywhere you should set source to 0.0.0.0/0
	// IP address allowed to access the service. In case you want to set the ip_access to anywhere you should set source to 0.0.0.0/0
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type IPAccessObservation struct {

	// (String) Description of the IP address.
	// Description of the IP address.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) IP address allowed to access the service. In case you want to set the ip_access to anywhere you should set source to 0.0.0.0/0
	// IP address allowed to access the service. In case you want to set the ip_access to anywhere you should set source to 0.0.0.0/0
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type IPAccessParameters struct {

	// (String) Description of the IP address.
	// Description of the IP address.
	// +kubebuilder:validation:Optional
	Description *string `json:"description" tf:"description,omitempty"`

	// (String) IP address allowed to access the service. In case you want to set the ip_access to anywhere you should set source to 0.0.0.0/0
	// IP address allowed to access the service. In case you want to set the ip_access to anywhere you should set source to 0.0.0.0/0
	// +kubebuilder:validation:Optional
	Source *string `json:"source" tf:"source,omitempty"`
}

type NativesecureInitParameters struct {
}

type NativesecureObservation struct {

	// (String) Endpoint host.
	// Endpoint host.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (Number) Endpoint port.
	// Endpoint port.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type NativesecureParameters struct {
}

type PrivateEndpointConfigInitParameters struct {
}

type PrivateEndpointConfigObservation struct {

	// (String) Unique identifier of the interface endpoint you created in your VPC with the AWS(Service Name) or GCP(Target Service) resource.
	// Unique identifier of the interface endpoint you created in your VPC with the AWS(Service Name) or GCP(Target Service) resource.
	EndpointServiceID *string `json:"endpointServiceId,omitempty" tf:"endpoint_service_id,omitempty"`

	// (String) Private DNS Hostname of the VPC you created.
	// Private DNS Hostname of the VPC you created.
	PrivateDNSHostname *string `json:"privateDnsHostname,omitempty" tf:"private_dns_hostname,omitempty"`
}

type PrivateEndpointConfigParameters struct {
}

type QueryAPIEndpointsInitParameters struct {

	// (List of String) The UUIDs of the API Keys to grant access to the query API.
	// The UUIDs of the API Keys to grant access to the query API.
	APIKeyIds []*string `json:"apiKeyIds,omitempty" tf:"api_key_ids,omitempty"`

	// origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
	// Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
	AllowedOrigins *string `json:"allowedOrigins,omitempty" tf:"allowed_origins,omitempty"`

	// (List of String) The Database role that will be used to run the query.
	// The Database role that will be used to run the query.
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`
}

type QueryAPIEndpointsObservation struct {

	// (List of String) The UUIDs of the API Keys to grant access to the query API.
	// The UUIDs of the API Keys to grant access to the query API.
	APIKeyIds []*string `json:"apiKeyIds,omitempty" tf:"api_key_ids,omitempty"`

	// origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
	// Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
	AllowedOrigins *string `json:"allowedOrigins,omitempty" tf:"allowed_origins,omitempty"`

	// (List of String) The Database role that will be used to run the query.
	// The Database role that will be used to run the query.
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`
}

type QueryAPIEndpointsParameters struct {

	// (List of String) The UUIDs of the API Keys to grant access to the query API.
	// The UUIDs of the API Keys to grant access to the query API.
	// +kubebuilder:validation:Optional
	APIKeyIds []*string `json:"apiKeyIds" tf:"api_key_ids,omitempty"`

	// origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
	// Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
	// +kubebuilder:validation:Optional
	AllowedOrigins *string `json:"allowedOrigins,omitempty" tf:"allowed_origins,omitempty"`

	// (List of String) The Database role that will be used to run the query.
	// The Database role that will be used to run the query.
	// +kubebuilder:validation:Optional
	Roles []*string `json:"roles" tf:"roles,omitempty"`
}

type ServiceInitParameters struct {

	// (Attributes) Configuration of service backup settings. (see below for nested schema)
	BackupConfiguration *BackupConfigurationInitParameters `json:"backupConfiguration,omitempty" tf:"backup_configuration,omitempty"`

	// (String) ID of the backup to restore when creating new service. If specified, the service will be created as a restore operation
	// ID of the backup to restore when creating new service. If specified, the service will be created as a restore operation
	BackupID *string `json:"backupId,omitempty" tf:"backup_id,omitempty"`

	// (String) BYOC ID related to the cloud provider account you want to create this service into.
	// BYOC ID related to the cloud provider account you want to create this service into.
	ByocID *string `json:"byocId,omitempty" tf:"byoc_id,omitempty"`

	// (String) Cloud provider ('aws', 'gcp', or 'azure') in which the service is deployed in.
	// Cloud provider ('aws', 'gcp', or 'azure') in which the service is deployed in.
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// (String) Compliance type of the service. Can be 'hipaa', 'pci'. Required for organizations that wish to deploy their services in the hipaa/pci compliant environment. NOTE: hipaa/pci compliance should be enabled for your ClickHouse organization before using this field.
	// Compliance type of the service. Can be 'hipaa', 'pci'. Required for organizations that wish to deploy their services in the hipaa/pci compliant environment. NOTE: hipaa/pci compliance should be enabled for your ClickHouse organization before using this field.
	ComplianceType *string `json:"complianceType,omitempty" tf:"compliance_type,omitempty"`

	// (String, Sensitive) Double SHA1 hash of password for connecting with the MySQL protocol. Cannot be specified if password or password_wo is specified.
	// Double SHA1 hash of password for connecting with the MySQL protocol. Cannot be specified if `password` or `password_wo` is specified.
	DoubleSha1PasswordHashSecretRef *v1.SecretKeySelector `json:"doubleSha1PasswordHashSecretRef,omitempty" tf:"-"`

	// (Boolean) Enable core dumps for the service.
	// Enable core dumps for the service.
	EnableCoreDumps *bool `json:"enableCoreDumps,omitempty" tf:"enable_core_dumps,omitempty"`

	// (String) Custom role identifier ARN.
	// Custom role identifier ARN.
	EncryptionAssumedRoleIdentifier *string `json:"encryptionAssumedRoleIdentifier,omitempty" tf:"encryption_assumed_role_identifier,omitempty"`

	// (String) Custom encryption key ARN.
	// Custom encryption key ARN.
	EncryptionKey *string `json:"encryptionKey,omitempty" tf:"encryption_key,omitempty"`

	// (Attributes) Allow to enable and configure additional endpoints (read protocols) to expose on the ClickHouse service. (see below for nested schema)
	Endpoints *EndpointsInitParameters `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	// (Attributes List) List of IP addresses allowed to access the service. (see below for nested schema)
	IPAccess []IPAccessInitParameters `json:"ipAccess,omitempty" tf:"ip_access,omitempty"`

	// (Boolean) When set to true the service is allowed to scale down to zero when idle.
	// When set to true the service is allowed to scale down to zero when idle.
	IdleScaling *bool `json:"idleScaling,omitempty" tf:"idle_scaling,omitempty"`

	// (Number) Set minimum idling timeout (in minutes). Must be greater than or equal to 5 minutes. Must be set if idle_scaling is enabled.
	// Set minimum idling timeout (in minutes). Must be greater than or equal to 5 minutes. Must be set if idle_scaling is enabled.
	IdleTimeoutMinutes *float64 `json:"idleTimeoutMinutes,omitempty" tf:"idle_timeout_minutes,omitempty"`

	// scaling in GiB.
	// Maximum memory of a single replica during auto-scaling in GiB.
	MaxReplicaMemoryGb *float64 `json:"maxReplicaMemoryGb,omitempty" tf:"max_replica_memory_gb,omitempty"`

	// scaling in GiB.
	// Maximum total memory of all workers during auto-scaling in GiB.
	MaxTotalMemoryGb *float64 `json:"maxTotalMemoryGb,omitempty" tf:"max_total_memory_gb,omitempty"`

	// scaling in GiB.
	// Minimum memory of a single replica during auto-scaling in GiB.
	MinReplicaMemoryGb *float64 `json:"minReplicaMemoryGb,omitempty" tf:"min_replica_memory_gb,omitempty"`

	// scaling in GiB.
	// Minimum total memory of all workers during auto-scaling in GiB.
	MinTotalMemoryGb *float64 `json:"minTotalMemoryGb,omitempty" tf:"min_total_memory_gb,omitempty"`

	// (String) User defined identifier for the service.
	// User defined identifier for the service.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Number of replicas for the service.
	// Number of replicas for the service.
	NumReplicas *float64 `json:"numReplicas,omitempty" tf:"num_replicas,omitempty"`

	// (String, Sensitive) SHA256 hash of password for the default user. One of either password, password_wo, or password_hash must be specified.
	// SHA256 hash of password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
	PasswordHashSecretRef *v1.SecretKeySelector `json:"passwordHashSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) Password for the default user. One of either password, password_wo, or password_hash must be specified.
	// Password for the default ClickHouse user.
	// When passwordSecretRef is set, that secret is used (Bring Your Own Password).
	// Otherwise a password is auto-generated and written to writeConnectionSecretToRef.
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// only) Password for the default user (write-only, not persisted to state).
	// Password for the default user (write-only, not persisted to state).
	PasswordWoSecretRef *v1.SecretKeySelector `json:"passwordWoSecretRef,omitempty" tf:"-"`

	// (Number) Version number for password_wo. Increment this to trigger a password update when using password_wo.
	// Version number for password_wo. Increment this to trigger a password update when using password_wo.
	PasswordWoVersion *float64 `json:"passwordWoVersion,omitempty" tf:"password_wo_version,omitempty"`

	// (Attributes) Configuration of the query API endpoints feature. (see below for nested schema)
	QueryAPIEndpoints *QueryAPIEndpointsInitParameters `json:"queryApiEndpoints,omitempty" tf:"query_api_endpoints,omitempty"`

	// flag set to true and then remove readonly flag completely, the provider won't detect the change. If you want to make a secondary service read write, explicitly set the readonly flag to false.
	// Indicates if this service should be read only. Only allowed for secondary services, those which share data with another service (i.e. when `warehouse_id` field is set).
	Readonly *bool `json:"readonly,omitempty" tf:"readonly,omitempty"`

	// (String) Region within the cloud provider in which the service is deployed in.
	// Region within the cloud provider in which the service is deployed in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Release channel to use for this service. Can be 'default', 'fast' or 'slow'.
	// Release channel to use for this service. Can be 'default', 'fast' or 'slow'.
	ReleaseChannel *string `json:"releaseChannel,omitempty" tf:"release_channel,omitempty"`

	// value pairs.
	// Tags associated with the service as key-value pairs.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Tier of the service: 'development', 'production'. Required for organizations using the Legacy ClickHouse Cloud Tiers, must be omitted for organizations using the new ClickHouse Cloud Tiers.
	// Tier of the service: 'development', 'production'. Required for organizations using the Legacy ClickHouse Cloud Tiers, must be omitted for organizations using the new ClickHouse Cloud Tiers.
	Tier *string `json:"tier,omitempty" tf:"tier,omitempty"`

	// (Attributes) Configuration of the Transparent Data Encryption (TDE) feature. Requires an organization with the Enterprise plan. (see below for nested schema)
	TransparentDataEncryption *TransparentDataEncryptionInitParameters `json:"transparentDataEncryption,omitempty" tf:"transparent_data_encryption,omitempty"`

	// set and then remove warehouse_id attribute completely, the provider won't detect the change. If you want to make a secondary service become primary, remove the warehouse_id and taint it before applying.
	// Set it to the 'warehouse_id' attribute of another service to share the data with it. The service must be in the same cloud and region.
	WarehouseID *string `json:"warehouseId,omitempty" tf:"warehouse_id,omitempty"`
}

type ServiceObservation struct {

	// (Attributes) Configuration of service backup settings. (see below for nested schema)
	BackupConfiguration *BackupConfigurationObservation `json:"backupConfiguration,omitempty" tf:"backup_configuration,omitempty"`

	// (String) ID of the backup to restore when creating new service. If specified, the service will be created as a restore operation
	// ID of the backup to restore when creating new service. If specified, the service will be created as a restore operation
	BackupID *string `json:"backupId,omitempty" tf:"backup_id,omitempty"`

	// (String) BYOC ID related to the cloud provider account you want to create this service into.
	// BYOC ID related to the cloud provider account you want to create this service into.
	ByocID *string `json:"byocId,omitempty" tf:"byoc_id,omitempty"`

	// (String) Cloud provider ('aws', 'gcp', or 'azure') in which the service is deployed in.
	// Cloud provider ('aws', 'gcp', or 'azure') in which the service is deployed in.
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// (String) Compliance type of the service. Can be 'hipaa', 'pci'. Required for organizations that wish to deploy their services in the hipaa/pci compliant environment. NOTE: hipaa/pci compliance should be enabled for your ClickHouse organization before using this field.
	// Compliance type of the service. Can be 'hipaa', 'pci'. Required for organizations that wish to deploy their services in the hipaa/pci compliant environment. NOTE: hipaa/pci compliance should be enabled for your ClickHouse organization before using this field.
	ComplianceType *string `json:"complianceType,omitempty" tf:"compliance_type,omitempty"`

	// (Boolean) Enable core dumps for the service.
	// Enable core dumps for the service.
	EnableCoreDumps *bool `json:"enableCoreDumps,omitempty" tf:"enable_core_dumps,omitempty"`

	// (String) Custom role identifier ARN.
	// Custom role identifier ARN.
	EncryptionAssumedRoleIdentifier *string `json:"encryptionAssumedRoleIdentifier,omitempty" tf:"encryption_assumed_role_identifier,omitempty"`

	// (String) Custom encryption key ARN.
	// Custom encryption key ARN.
	EncryptionKey *string `json:"encryptionKey,omitempty" tf:"encryption_key,omitempty"`

	// (Attributes) Allow to enable and configure additional endpoints (read protocols) to expose on the ClickHouse service. (see below for nested schema)
	Endpoints *EndpointsObservation `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	// (String) IAM role used for accessing objects in s3.
	// IAM role used for accessing objects in s3.
	IAMRole *string `json:"iamRole,omitempty" tf:"iam_role,omitempty"`

	// (String) ID of the created service. Generated by ClickHouse Cloud.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes List) List of IP addresses allowed to access the service. (see below for nested schema)
	IPAccess []IPAccessObservation `json:"ipAccess,omitempty" tf:"ip_access,omitempty"`

	// (Boolean) When set to true the service is allowed to scale down to zero when idle.
	// When set to true the service is allowed to scale down to zero when idle.
	IdleScaling *bool `json:"idleScaling,omitempty" tf:"idle_scaling,omitempty"`

	// (Number) Set minimum idling timeout (in minutes). Must be greater than or equal to 5 minutes. Must be set if idle_scaling is enabled.
	// Set minimum idling timeout (in minutes). Must be greater than or equal to 5 minutes. Must be set if idle_scaling is enabled.
	IdleTimeoutMinutes *float64 `json:"idleTimeoutMinutes,omitempty" tf:"idle_timeout_minutes,omitempty"`

	// (Boolean) If true, it indicates this is a primary service using its own data. If false it means this service is a secondary service, thus using data from a warehouse.
	// If true, it indicates this is a primary service using its own data. If false it means this service is a secondary service, thus using data from a warehouse.
	IsPrimary *bool `json:"isPrimary,omitempty" tf:"is_primary,omitempty"`

	// scaling in GiB.
	// Maximum memory of a single replica during auto-scaling in GiB.
	MaxReplicaMemoryGb *float64 `json:"maxReplicaMemoryGb,omitempty" tf:"max_replica_memory_gb,omitempty"`

	// scaling in GiB.
	// Maximum total memory of all workers during auto-scaling in GiB.
	MaxTotalMemoryGb *float64 `json:"maxTotalMemoryGb,omitempty" tf:"max_total_memory_gb,omitempty"`

	// scaling in GiB.
	// Minimum memory of a single replica during auto-scaling in GiB.
	MinReplicaMemoryGb *float64 `json:"minReplicaMemoryGb,omitempty" tf:"min_replica_memory_gb,omitempty"`

	// scaling in GiB.
	// Minimum total memory of all workers during auto-scaling in GiB.
	MinTotalMemoryGb *float64 `json:"minTotalMemoryGb,omitempty" tf:"min_total_memory_gb,omitempty"`

	// (String) User defined identifier for the service.
	// User defined identifier for the service.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Number of replicas for the service.
	// Number of replicas for the service.
	NumReplicas *float64 `json:"numReplicas,omitempty" tf:"num_replicas,omitempty"`

	// (Number) Version number for password_wo. Increment this to trigger a password update when using password_wo.
	// Version number for password_wo. Increment this to trigger a password update when using password_wo.
	PasswordWoVersion *float64 `json:"passwordWoVersion,omitempty" tf:"password_wo_version,omitempty"`

	// (Attributes) Service config for private endpoints (see below for nested schema)
	PrivateEndpointConfig *PrivateEndpointConfigObservation `json:"privateEndpointConfig,omitempty" tf:"private_endpoint_config,omitempty"`

	// (Attributes) Configuration of the query API endpoints feature. (see below for nested schema)
	QueryAPIEndpoints *QueryAPIEndpointsObservation `json:"queryApiEndpoints,omitempty" tf:"query_api_endpoints,omitempty"`

	// flag set to true and then remove readonly flag completely, the provider won't detect the change. If you want to make a secondary service read write, explicitly set the readonly flag to false.
	// Indicates if this service should be read only. Only allowed for secondary services, those which share data with another service (i.e. when `warehouse_id` field is set).
	Readonly *bool `json:"readonly,omitempty" tf:"readonly,omitempty"`

	// (String) Region within the cloud provider in which the service is deployed in.
	// Region within the cloud provider in which the service is deployed in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Release channel to use for this service. Can be 'default', 'fast' or 'slow'.
	// Release channel to use for this service. Can be 'default', 'fast' or 'slow'.
	ReleaseChannel *string `json:"releaseChannel,omitempty" tf:"release_channel,omitempty"`

	// value pairs.
	// Tags associated with the service as key-value pairs.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Tier of the service: 'development', 'production'. Required for organizations using the Legacy ClickHouse Cloud Tiers, must be omitted for organizations using the new ClickHouse Cloud Tiers.
	// Tier of the service: 'development', 'production'. Required for organizations using the Legacy ClickHouse Cloud Tiers, must be omitted for organizations using the new ClickHouse Cloud Tiers.
	Tier *string `json:"tier,omitempty" tf:"tier,omitempty"`

	// (Attributes) Configuration of the Transparent Data Encryption (TDE) feature. Requires an organization with the Enterprise plan. (see below for nested schema)
	TransparentDataEncryption *TransparentDataEncryptionObservation `json:"transparentDataEncryption,omitempty" tf:"transparent_data_encryption,omitempty"`

	// set and then remove warehouse_id attribute completely, the provider won't detect the change. If you want to make a secondary service become primary, remove the warehouse_id and taint it before applying.
	// Set it to the 'warehouse_id' attribute of another service to share the data with it. The service must be in the same cloud and region.
	WarehouseID *string `json:"warehouseId,omitempty" tf:"warehouse_id,omitempty"`
}

type ServiceParameters struct {

	// (Attributes) Configuration of service backup settings. (see below for nested schema)
	// +kubebuilder:validation:Optional
	BackupConfiguration *BackupConfigurationParameters `json:"backupConfiguration,omitempty" tf:"backup_configuration,omitempty"`

	// (String) ID of the backup to restore when creating new service. If specified, the service will be created as a restore operation
	// ID of the backup to restore when creating new service. If specified, the service will be created as a restore operation
	// +kubebuilder:validation:Optional
	BackupID *string `json:"backupId,omitempty" tf:"backup_id,omitempty"`

	// (String) BYOC ID related to the cloud provider account you want to create this service into.
	// BYOC ID related to the cloud provider account you want to create this service into.
	// +kubebuilder:validation:Optional
	ByocID *string `json:"byocId,omitempty" tf:"byoc_id,omitempty"`

	// (String) Cloud provider ('aws', 'gcp', or 'azure') in which the service is deployed in.
	// Cloud provider ('aws', 'gcp', or 'azure') in which the service is deployed in.
	// +kubebuilder:validation:Optional
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// (String) Compliance type of the service. Can be 'hipaa', 'pci'. Required for organizations that wish to deploy their services in the hipaa/pci compliant environment. NOTE: hipaa/pci compliance should be enabled for your ClickHouse organization before using this field.
	// Compliance type of the service. Can be 'hipaa', 'pci'. Required for organizations that wish to deploy their services in the hipaa/pci compliant environment. NOTE: hipaa/pci compliance should be enabled for your ClickHouse organization before using this field.
	// +kubebuilder:validation:Optional
	ComplianceType *string `json:"complianceType,omitempty" tf:"compliance_type,omitempty"`

	// (String, Sensitive) Double SHA1 hash of password for connecting with the MySQL protocol. Cannot be specified if password or password_wo is specified.
	// Double SHA1 hash of password for connecting with the MySQL protocol. Cannot be specified if `password` or `password_wo` is specified.
	// +kubebuilder:validation:Optional
	DoubleSha1PasswordHashSecretRef *v1.SecretKeySelector `json:"doubleSha1PasswordHashSecretRef,omitempty" tf:"-"`

	// (Boolean) Enable core dumps for the service.
	// Enable core dumps for the service.
	// +kubebuilder:validation:Optional
	EnableCoreDumps *bool `json:"enableCoreDumps,omitempty" tf:"enable_core_dumps,omitempty"`

	// (String) Custom role identifier ARN.
	// Custom role identifier ARN.
	// +kubebuilder:validation:Optional
	EncryptionAssumedRoleIdentifier *string `json:"encryptionAssumedRoleIdentifier,omitempty" tf:"encryption_assumed_role_identifier,omitempty"`

	// (String) Custom encryption key ARN.
	// Custom encryption key ARN.
	// +kubebuilder:validation:Optional
	EncryptionKey *string `json:"encryptionKey,omitempty" tf:"encryption_key,omitempty"`

	// (Attributes) Allow to enable and configure additional endpoints (read protocols) to expose on the ClickHouse service. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Endpoints *EndpointsParameters `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	// (Attributes List) List of IP addresses allowed to access the service. (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPAccess []IPAccessParameters `json:"ipAccess,omitempty" tf:"ip_access,omitempty"`

	// (Boolean) When set to true the service is allowed to scale down to zero when idle.
	// When set to true the service is allowed to scale down to zero when idle.
	// +kubebuilder:validation:Optional
	IdleScaling *bool `json:"idleScaling,omitempty" tf:"idle_scaling,omitempty"`

	// (Number) Set minimum idling timeout (in minutes). Must be greater than or equal to 5 minutes. Must be set if idle_scaling is enabled.
	// Set minimum idling timeout (in minutes). Must be greater than or equal to 5 minutes. Must be set if idle_scaling is enabled.
	// +kubebuilder:validation:Optional
	IdleTimeoutMinutes *float64 `json:"idleTimeoutMinutes,omitempty" tf:"idle_timeout_minutes,omitempty"`

	// scaling in GiB.
	// Maximum memory of a single replica during auto-scaling in GiB.
	// +kubebuilder:validation:Optional
	MaxReplicaMemoryGb *float64 `json:"maxReplicaMemoryGb,omitempty" tf:"max_replica_memory_gb,omitempty"`

	// scaling in GiB.
	// Maximum total memory of all workers during auto-scaling in GiB.
	// +kubebuilder:validation:Optional
	MaxTotalMemoryGb *float64 `json:"maxTotalMemoryGb,omitempty" tf:"max_total_memory_gb,omitempty"`

	// scaling in GiB.
	// Minimum memory of a single replica during auto-scaling in GiB.
	// +kubebuilder:validation:Optional
	MinReplicaMemoryGb *float64 `json:"minReplicaMemoryGb,omitempty" tf:"min_replica_memory_gb,omitempty"`

	// scaling in GiB.
	// Minimum total memory of all workers during auto-scaling in GiB.
	// +kubebuilder:validation:Optional
	MinTotalMemoryGb *float64 `json:"minTotalMemoryGb,omitempty" tf:"min_total_memory_gb,omitempty"`

	// (String) User defined identifier for the service.
	// User defined identifier for the service.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Number of replicas for the service.
	// Number of replicas for the service.
	// +kubebuilder:validation:Optional
	NumReplicas *float64 `json:"numReplicas,omitempty" tf:"num_replicas,omitempty"`

	// (String, Sensitive) SHA256 hash of password for the default user. One of either password, password_wo, or password_hash must be specified.
	// SHA256 hash of password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
	// +kubebuilder:validation:Optional
	PasswordHashSecretRef *v1.SecretKeySelector `json:"passwordHashSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) Password for the default user. One of either password, password_wo, or password_hash must be specified.
	// Password for the default ClickHouse user.
	// When passwordSecretRef is set, that secret is used (Bring Your Own Password).
	// Otherwise a password is auto-generated and written to writeConnectionSecretToRef.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// only) Password for the default user (write-only, not persisted to state).
	// Password for the default user (write-only, not persisted to state).
	// +kubebuilder:validation:Optional
	PasswordWoSecretRef *v1.SecretKeySelector `json:"passwordWoSecretRef,omitempty" tf:"-"`

	// (Number) Version number for password_wo. Increment this to trigger a password update when using password_wo.
	// Version number for password_wo. Increment this to trigger a password update when using password_wo.
	// +kubebuilder:validation:Optional
	PasswordWoVersion *float64 `json:"passwordWoVersion,omitempty" tf:"password_wo_version,omitempty"`

	// (Attributes) Configuration of the query API endpoints feature. (see below for nested schema)
	// +kubebuilder:validation:Optional
	QueryAPIEndpoints *QueryAPIEndpointsParameters `json:"queryApiEndpoints,omitempty" tf:"query_api_endpoints,omitempty"`

	// flag set to true and then remove readonly flag completely, the provider won't detect the change. If you want to make a secondary service read write, explicitly set the readonly flag to false.
	// Indicates if this service should be read only. Only allowed for secondary services, those which share data with another service (i.e. when `warehouse_id` field is set).
	// +kubebuilder:validation:Optional
	Readonly *bool `json:"readonly,omitempty" tf:"readonly,omitempty"`

	// (String) Region within the cloud provider in which the service is deployed in.
	// Region within the cloud provider in which the service is deployed in.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Release channel to use for this service. Can be 'default', 'fast' or 'slow'.
	// Release channel to use for this service. Can be 'default', 'fast' or 'slow'.
	// +kubebuilder:validation:Optional
	ReleaseChannel *string `json:"releaseChannel,omitempty" tf:"release_channel,omitempty"`

	// value pairs.
	// Tags associated with the service as key-value pairs.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Tier of the service: 'development', 'production'. Required for organizations using the Legacy ClickHouse Cloud Tiers, must be omitted for organizations using the new ClickHouse Cloud Tiers.
	// Tier of the service: 'development', 'production'. Required for organizations using the Legacy ClickHouse Cloud Tiers, must be omitted for organizations using the new ClickHouse Cloud Tiers.
	// +kubebuilder:validation:Optional
	Tier *string `json:"tier,omitempty" tf:"tier,omitempty"`

	// (Attributes) Configuration of the Transparent Data Encryption (TDE) feature. Requires an organization with the Enterprise plan. (see below for nested schema)
	// +kubebuilder:validation:Optional
	TransparentDataEncryption *TransparentDataEncryptionParameters `json:"transparentDataEncryption,omitempty" tf:"transparent_data_encryption,omitempty"`

	// set and then remove warehouse_id attribute completely, the provider won't detect the change. If you want to make a secondary service become primary, remove the warehouse_id and taint it before applying.
	// Set it to the 'warehouse_id' attribute of another service to share the data with it. The service must be in the same cloud and region.
	// +kubebuilder:validation:Optional
	WarehouseID *string `json:"warehouseId,omitempty" tf:"warehouse_id,omitempty"`
}

type TransparentDataEncryptionInitParameters struct {

	// (Boolean) Wether to enable the mysql endpoint or not.
	// If true, TDE is enabled for the service.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type TransparentDataEncryptionObservation struct {

	// (Boolean) Wether to enable the mysql endpoint or not.
	// If true, TDE is enabled for the service.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) ID of Role to be used for granting access to the Encryption Key. This is an ARN for AWS services and a Service Account Identifier for GCP.
	// ID of Role to be used for granting access to the Encryption Key. This is an ARN for AWS services and a Service Account Identifier for GCP.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`
}

type TransparentDataEncryptionParameters struct {

	// (Boolean) Wether to enable the mysql endpoint or not.
	// If true, TDE is enabled for the service.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

// ServiceSpec defines the desired state of Service
type ServiceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServiceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServiceInitParameters `json:"initProvider,omitempty"`
}

// ServiceStatus defines the observed state of Service.
type ServiceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServiceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Service is the Schema for the Services API. You can use the clickhouse_service resource to deploy ClickHouse cloud instances on supported cloud providers. Known limitations: If you create a service with warehouse_id set and then remove warehouse_id attribute completely, the provider won't detect the change. If you want to make a secondary service become primary, remove the warehouse_id and taint it before applying.If you create a service with readonly flag set to true and then remove readonly flag completely, the provider won't detect the change. If you want to make a secondary service read write, explicitly set the readonly flag to false.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhouse}
type Service struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cloudProvider) || (has(self.initProvider) && has(self.initProvider.cloudProvider))",message="spec.forProvider.cloudProvider is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ipAccess) || (has(self.initProvider) && has(self.initProvider.ipAccess))",message="spec.forProvider.ipAccess is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	Spec   ServiceSpec   `json:"spec"`
	Status ServiceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceList contains a list of Services
type ServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Service `json:"items"`
}

// Repository type metadata.
var (
	Service_Kind             = "Service"
	Service_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Service_Kind}.String()
	Service_KindAPIVersion   = Service_Kind + "." + CRDGroupVersion.String()
	Service_GroupVersionKind = CRDGroupVersion.WithKind(Service_Kind)
)

func init() {
	SchemeBuilder.Register(&Service{}, &ServiceList{})
}
