// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type APIEndpointInitParameters struct {

	// (Set of String) API key IDs allowed to call the endpoint.
	// API key IDs allowed to call the endpoint.
	// +listType=set
	APIKeyIds []*string `json:"apiKeyIds,omitempty" tf:"api_key_ids,omitempty"`

	// (Set of String) Origins allowed by the endpoint CORS policy. Omit this field to restrict access to backend servers.
	// Origins allowed by the endpoint CORS policy. Omit this field to restrict access to backend servers.
	// +listType=set
	AllowedOrigins []*string `json:"allowedOrigins,omitempty" tf:"allowed_origins,omitempty"`

	// (String) Database used by the Query API endpoint.
	// Database used by the Query API endpoint.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) Name of the Query API endpoint.
	// Name of the Query API endpoint.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Map of String) Default query parameters.
	// Default query parameters.
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (Set of String) Database roles used to run the query.
	// Database roles used to run the query.
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) SQL executed by the endpoint.
	// SQL executed by the endpoint.
	SQL *string `json:"sql,omitempty" tf:"sql,omitempty"`

	// (String) ID of the ClickHouse Cloud service that runs the query.
	// ID of the ClickHouse Cloud service that runs the query.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickhouse/v1alpha1.Service
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// Reference to a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDRef *v2.Reference `json:"serviceIdRef,omitempty" tf:"-"`

	// Selector for a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDSelector *v2.Selector `json:"serviceIdSelector,omitempty" tf:"-"`
}

type APIEndpointObservation struct {

	// (Set of String) API key IDs allowed to call the endpoint.
	// API key IDs allowed to call the endpoint.
	// +listType=set
	APIKeyIds []*string `json:"apiKeyIds,omitempty" tf:"api_key_ids,omitempty"`

	// (Set of String) Origins allowed by the endpoint CORS policy. Omit this field to restrict access to backend servers.
	// Origins allowed by the endpoint CORS policy. Omit this field to restrict access to backend servers.
	// +listType=set
	AllowedOrigins []*string `json:"allowedOrigins,omitempty" tf:"allowed_origins,omitempty"`

	// (String) Database used by the Query API endpoint.
	// Database used by the Query API endpoint.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) Unique ID of the Query API endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the Query API endpoint.
	// Name of the Query API endpoint.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Map of String) Default query parameters.
	// Default query parameters.
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (Set of String) Database roles used to run the query.
	// Database roles used to run the query.
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) SQL executed by the endpoint.
	// SQL executed by the endpoint.
	SQL *string `json:"sql,omitempty" tf:"sql,omitempty"`

	// (String) ID of the ClickHouse Cloud service that runs the query.
	// ID of the ClickHouse Cloud service that runs the query.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) Public URL used to execute the endpoint.
	// Public URL used to execute the endpoint.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type APIEndpointParameters struct {

	// (Set of String) API key IDs allowed to call the endpoint.
	// API key IDs allowed to call the endpoint.
	// +kubebuilder:validation:Optional
	// +listType=set
	APIKeyIds []*string `json:"apiKeyIds,omitempty" tf:"api_key_ids,omitempty"`

	// (Set of String) Origins allowed by the endpoint CORS policy. Omit this field to restrict access to backend servers.
	// Origins allowed by the endpoint CORS policy. Omit this field to restrict access to backend servers.
	// +kubebuilder:validation:Optional
	// +listType=set
	AllowedOrigins []*string `json:"allowedOrigins,omitempty" tf:"allowed_origins,omitempty"`

	// (String) Database used by the Query API endpoint.
	// Database used by the Query API endpoint.
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) Name of the Query API endpoint.
	// Name of the Query API endpoint.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Map of String) Default query parameters.
	// Default query parameters.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (Set of String) Database roles used to run the query.
	// Database roles used to run the query.
	// +kubebuilder:validation:Optional
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) SQL executed by the endpoint.
	// SQL executed by the endpoint.
	// +kubebuilder:validation:Optional
	SQL *string `json:"sql,omitempty" tf:"sql,omitempty"`

	// (String) ID of the ClickHouse Cloud service that runs the query.
	// ID of the ClickHouse Cloud service that runs the query.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickhouse/v1alpha1.Service
	// +kubebuilder:validation:Optional
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// Reference to a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDRef *v2.Reference `json:"serviceIdRef,omitempty" tf:"-"`

	// Selector for a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDSelector *v2.Selector `json:"serviceIdSelector,omitempty" tf:"-"`
}

// APIEndpointSpec defines the desired state of APIEndpoint
type APIEndpointSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   APIEndpointParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider APIEndpointInitParameters `json:"initProvider,omitempty"`
}

// APIEndpointStatus defines the observed state of APIEndpoint.
type APIEndpointStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               APIEndpointObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// APIEndpoint is the Schema for the APIEndpoints API. Use this resource to create a Query API endpoint from a SQL query in ClickHouse Cloud. The endpoint runs the query over HTTP, so callers do not need a native driver to connect to the ClickHouse Cloud service. You can configure query parameters, API keys, database roles, and CORS allowed domains. For more information, see Setting up query API endpoints https://clickhouse.com/docs/products/cloud/guides/sql-console/query-endpoints. ~> Note: This resource is in beta. Its behavior may change in future provider versions. You can import an existing endpoint if it was created through the Query API endpoints API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhouse}
type APIEndpoint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.apiKeyIds) || (has(self.initProvider) && has(self.initProvider.apiKeyIds))",message="spec.forProvider.apiKeyIds is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.database) || (has(self.initProvider) && has(self.initProvider.database))",message="spec.forProvider.database is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roles) || (has(self.initProvider) && has(self.initProvider.roles))",message="spec.forProvider.roles is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sql) || (has(self.initProvider) && has(self.initProvider.sql))",message="spec.forProvider.sql is a required parameter"
	Spec   APIEndpointSpec   `json:"spec"`
	Status APIEndpointStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// APIEndpointList contains a list of APIEndpoints
type APIEndpointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []APIEndpoint `json:"items"`
}

// Repository type metadata.
var (
	APIEndpoint_Kind             = "APIEndpoint"
	APIEndpoint_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: APIEndpoint_Kind}.String()
	APIEndpoint_KindAPIVersion   = APIEndpoint_Kind + "." + CRDGroupVersion.String()
	APIEndpoint_GroupVersionKind = CRDGroupVersion.WithKind(APIEndpoint_Kind)
)

func init() {
	SchemeBuilder.Register(&APIEndpoint{}, &APIEndpointList{})
}
