// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SavedQueryInitParameters struct {

	// (String) Database used by the saved query.
	// Database used by the saved query.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) Name of the saved query.
	// Name of the saved query.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Map of String) Default query parameters.
	// Default query parameters.
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) Saved SQL query.
	// Saved SQL query.
	SQL *string `json:"sql,omitempty" tf:"sql,omitempty"`

	// (String) ID of the ClickHouse Cloud service for the saved query.
	// ID of the ClickHouse Cloud service for the saved query.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickhouse/v1alpha1.Service
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// Reference to a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDRef *v2.Reference `json:"serviceIdRef,omitempty" tf:"-"`

	// Selector for a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDSelector *v2.Selector `json:"serviceIdSelector,omitempty" tf:"-"`
}

type SavedQueryObservation struct {

	// (String) Database used by the saved query.
	// Database used by the saved query.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) Unique ID of the saved query.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the saved query.
	// Name of the saved query.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Map of String) Default query parameters.
	// Default query parameters.
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) Saved SQL query.
	// Saved SQL query.
	SQL *string `json:"sql,omitempty" tf:"sql,omitempty"`

	// (String) ID of the ClickHouse Cloud service for the saved query.
	// ID of the ClickHouse Cloud service for the saved query.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`
}

type SavedQueryParameters struct {

	// (String) Database used by the saved query.
	// Database used by the saved query.
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) Name of the saved query.
	// Name of the saved query.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Map of String) Default query parameters.
	// Default query parameters.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) Saved SQL query.
	// Saved SQL query.
	// +kubebuilder:validation:Optional
	SQL *string `json:"sql,omitempty" tf:"sql,omitempty"`

	// (String) ID of the ClickHouse Cloud service for the saved query.
	// ID of the ClickHouse Cloud service for the saved query.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickhouse/v1alpha1.Service
	// +kubebuilder:validation:Optional
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// Reference to a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDRef *v2.Reference `json:"serviceIdRef,omitempty" tf:"-"`

	// Selector for a Service in clickhouse to populate serviceId.
	// +kubebuilder:validation:Optional
	ServiceIDSelector *v2.Selector `json:"serviceIdSelector,omitempty" tf:"-"`
}

// SavedQuerySpec defines the desired state of SavedQuery
type SavedQuerySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   SavedQueryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SavedQueryInitParameters `json:"initProvider,omitempty"`
}

// SavedQueryStatus defines the observed state of SavedQuery.
type SavedQueryStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SavedQueryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SavedQuery is the Schema for the SavedQuerys API. Use this resource to save a named SQL query for a ClickHouse Cloud service. The saved query can be opened and run in the SQL console. For more information, see Saving a query https://clickhouse.com/docs/products/cloud/features/sql-console-features/sql-console#saving-a-query. ~> Note: This resource is in beta. Its behavior may change in future provider versions. You can import an existing saved query if it was created through the saved queries API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhouse}
type SavedQuery struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.database) || (has(self.initProvider) && has(self.initProvider.database))",message="spec.forProvider.database is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sql) || (has(self.initProvider) && has(self.initProvider.sql))",message="spec.forProvider.sql is a required parameter"
	Spec   SavedQuerySpec   `json:"spec"`
	Status SavedQueryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SavedQueryList contains a list of SavedQuerys
type SavedQueryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SavedQuery `json:"items"`
}

// Repository type metadata.
var (
	SavedQuery_Kind             = "SavedQuery"
	SavedQuery_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SavedQuery_Kind}.String()
	SavedQuery_KindAPIVersion   = SavedQuery_Kind + "." + CRDGroupVersion.String()
	SavedQuery_GroupVersionKind = CRDGroupVersion.WithKind(SavedQuery_Kind)
)

func init() {
	SchemeBuilder.Register(&SavedQuery{}, &SavedQueryList{})
}
