// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"

// GetCondition of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) GetProviderConfigReference() *xpv1.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) SetProviderConfigReference(r *xpv1.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) SetWriteConnectionSecretToReference(r *xpv1.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) GetProviderConfigReference() *xpv1.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) SetProviderConfigReference(r *xpv1.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) SetWriteConnectionSecretToReference(r *xpv1.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
