// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PoliciesInitParameters struct {

	// (String) Whether this policy allows or denies the specified permissions.
	// Whether this policy allows or denies the specified permissions.
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// (Set of String) List of permission strings granted or denied by this policy.
	// List of permission strings granted or denied by this policy.
	// +listType=set
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// (Set of String) List of resources this policy applies to. Format: 'instance/' or 'instance/*'.
	// List of resources this policy applies to. Format: 'instance/<uuid>' or 'instance/*'.
	// +listType=set
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`

	// (Attributes) Optional tags for additional policy metadata. (see below for nested schema)
	Tags *TagsInitParameters `json:"tags,omitempty" tf:"tags,omitempty"`
}

type PoliciesObservation struct {

	// (String) Whether this policy allows or denies the specified permissions.
	// Whether this policy allows or denies the specified permissions.
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// (String) Unique identifier for the role.
	// Server-assigned policy ID. Changes on every update since the server replaces all policies on PATCH.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) List of permission strings granted or denied by this policy.
	// List of permission strings granted or denied by this policy.
	// +listType=set
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// (Set of String) List of resources this policy applies to. Format: 'instance/' or 'instance/*'.
	// List of resources this policy applies to. Format: 'instance/<uuid>' or 'instance/*'.
	// +listType=set
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`

	// (String) ID of the role this policy belongs to.
	// ID of the role this policy belongs to.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// (Attributes) Optional tags for additional policy metadata. (see below for nested schema)
	Tags *TagsObservation `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Tenant ID that owns this role.
	// Tenant ID that owns this policy.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type PoliciesParameters struct {

	// (String) Whether this policy allows or denies the specified permissions.
	// Whether this policy allows or denies the specified permissions.
	// +kubebuilder:validation:Optional
	Effect *string `json:"effect" tf:"effect,omitempty"`

	// (Set of String) List of permission strings granted or denied by this policy.
	// List of permission strings granted or denied by this policy.
	// +kubebuilder:validation:Optional
	// +listType=set
	Permissions []*string `json:"permissions" tf:"permissions,omitempty"`

	// (Set of String) List of resources this policy applies to. Format: 'instance/' or 'instance/*'.
	// List of resources this policy applies to. Format: 'instance/<uuid>' or 'instance/*'.
	// +kubebuilder:validation:Optional
	// +listType=set
	Resources []*string `json:"resources" tf:"resources,omitempty"`

	// (Attributes) Optional tags for additional policy metadata. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Tags *TagsParameters `json:"tags,omitempty" tf:"tags,omitempty"`
}

type RoleInitParameters struct {

	// (String) Name of the custom role.
	// Name of the custom role.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) List of policies attached to this role. (see below for nested schema)
	Policies []PoliciesInitParameters `json:"policies,omitempty" tf:"policies,omitempty"`
}

type RoleObservation struct {

	// (String) Timestamp when the role was created.
	// Timestamp when the role was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Unique identifier for the role.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the custom role.
	// Name of the custom role.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Owner ID of this role.
	// Owner ID of this role.
	OwnerID *string `json:"ownerId,omitempty" tf:"owner_id,omitempty"`

	// (Attributes List) List of policies attached to this role. (see below for nested schema)
	Policies []PoliciesObservation `json:"policies,omitempty" tf:"policies,omitempty"`

	// (String) Tenant ID that owns this role.
	// Tenant ID that owns this role.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// (String) Type of the role. Always 'custom' for managed roles.
	// Type of the role. Always 'custom' for managed roles.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Timestamp when the role was last updated.
	// Timestamp when the role was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type RoleParameters struct {

	// (String) Name of the custom role.
	// Name of the custom role.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) List of policies attached to this role. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Policies []PoliciesParameters `json:"policies,omitempty" tf:"policies,omitempty"`
}

type TagsInitParameters struct {

	// console-admin (full access), sql-console-readonly (read-only).
	// SQL console role level for passwordless DB access. One of: sql-console-admin (full access), sql-console-readonly (read-only).
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type TagsObservation struct {

	// console-admin (full access), sql-console-readonly (read-only).
	// SQL console role level for passwordless DB access. One of: sql-console-admin (full access), sql-console-readonly (read-only).
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type TagsParameters struct {

	// console-admin (full access), sql-console-readonly (read-only).
	// SQL console role level for passwordless DB access. One of: sql-console-admin (full access), sql-console-readonly (read-only).
	// +kubebuilder:validation:Optional
	Role *string `json:"role" tf:"role,omitempty"`
}

// RoleSpec defines the desired state of Role
type RoleSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   RoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RoleInitParameters `json:"initProvider,omitempty"`
}

// RoleStatus defines the observed state of Role.
type RoleStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Role is the Schema for the Roles API. You can use the clickhouse_role resource to manage custom RBAC roles in ClickHouse Cloud. Example Usage
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhouse}
type Role struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RoleSpec   `json:"spec"`
	Status RoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoleList contains a list of Roles
type RoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Role `json:"items"`
}

// Repository type metadata.
var (
	Role_Kind             = "Role"
	Role_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Role_Kind}.String()
	Role_KindAPIVersion   = Role_Kind + "." + CRDGroupVersion.String()
	Role_GroupVersionKind = CRDGroupVersion.WithKind(Role_Kind)
)

func init() {
	SchemeBuilder.Register(&Role{}, &RoleList{})
}
