//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachment) DeepCopyInto(out *PrivateEndpointsAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachment.
func (in *PrivateEndpointsAttachment) DeepCopy() *PrivateEndpointsAttachment {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateEndpointsAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachmentInitParameters) DeepCopyInto(out *PrivateEndpointsAttachmentInitParameters) {
	*out = *in
	if in.PrivateEndpointIds != nil {
		in, out := &in.PrivateEndpointIds, &out.PrivateEndpointIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachmentInitParameters.
func (in *PrivateEndpointsAttachmentInitParameters) DeepCopy() *PrivateEndpointsAttachmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachmentList) DeepCopyInto(out *PrivateEndpointsAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrivateEndpointsAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachmentList.
func (in *PrivateEndpointsAttachmentList) DeepCopy() *PrivateEndpointsAttachmentList {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateEndpointsAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachmentObservation) DeepCopyInto(out *PrivateEndpointsAttachmentObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PrivateEndpointIds != nil {
		in, out := &in.PrivateEndpointIds, &out.PrivateEndpointIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachmentObservation.
func (in *PrivateEndpointsAttachmentObservation) DeepCopy() *PrivateEndpointsAttachmentObservation {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachmentParameters) DeepCopyInto(out *PrivateEndpointsAttachmentParameters) {
	*out = *in
	if in.PrivateEndpointIds != nil {
		in, out := &in.PrivateEndpointIds, &out.PrivateEndpointIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachmentParameters.
func (in *PrivateEndpointsAttachmentParameters) DeepCopy() *PrivateEndpointsAttachmentParameters {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachmentSpec) DeepCopyInto(out *PrivateEndpointsAttachmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachmentSpec.
func (in *PrivateEndpointsAttachmentSpec) DeepCopy() *PrivateEndpointsAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachmentStatus) DeepCopyInto(out *PrivateEndpointsAttachmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachmentStatus.
func (in *PrivateEndpointsAttachmentStatus) DeepCopy() *PrivateEndpointsAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociation) DeepCopyInto(out *TransparentDataEncryptionKeyAssociation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociation.
func (in *TransparentDataEncryptionKeyAssociation) DeepCopy() *TransparentDataEncryptionKeyAssociation {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransparentDataEncryptionKeyAssociation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociationInitParameters) DeepCopyInto(out *TransparentDataEncryptionKeyAssociationInitParameters) {
	*out = *in
	if in.KeyID != nil {
		in, out := &in.KeyID, &out.KeyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociationInitParameters.
func (in *TransparentDataEncryptionKeyAssociationInitParameters) DeepCopy() *TransparentDataEncryptionKeyAssociationInitParameters {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociationList) DeepCopyInto(out *TransparentDataEncryptionKeyAssociationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TransparentDataEncryptionKeyAssociation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociationList.
func (in *TransparentDataEncryptionKeyAssociationList) DeepCopy() *TransparentDataEncryptionKeyAssociationList {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransparentDataEncryptionKeyAssociationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociationObservation) DeepCopyInto(out *TransparentDataEncryptionKeyAssociationObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.KeyID != nil {
		in, out := &in.KeyID, &out.KeyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociationObservation.
func (in *TransparentDataEncryptionKeyAssociationObservation) DeepCopy() *TransparentDataEncryptionKeyAssociationObservation {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociationParameters) DeepCopyInto(out *TransparentDataEncryptionKeyAssociationParameters) {
	*out = *in
	if in.KeyID != nil {
		in, out := &in.KeyID, &out.KeyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociationParameters.
func (in *TransparentDataEncryptionKeyAssociationParameters) DeepCopy() *TransparentDataEncryptionKeyAssociationParameters {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociationSpec) DeepCopyInto(out *TransparentDataEncryptionKeyAssociationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociationSpec.
func (in *TransparentDataEncryptionKeyAssociationSpec) DeepCopy() *TransparentDataEncryptionKeyAssociationSpec {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociationStatus) DeepCopyInto(out *TransparentDataEncryptionKeyAssociationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociationStatus.
func (in *TransparentDataEncryptionKeyAssociationStatus) DeepCopy() *TransparentDataEncryptionKeyAssociationStatus {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociationStatus)
	in.DeepCopyInto(out)
	return out
}
