// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Service.
func (mg *Service) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ReadReplicaOf),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ReadReplicaOfRef,
		Selector:     mg.Spec.ForProvider.ReadReplicaOfSelector,
		To: reference.To{
			List:    &ServiceList{},
			Managed: &Service{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ReadReplicaOf")
	}
	mg.Spec.ForProvider.ReadReplicaOf = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ReadReplicaOfRef = rsp.ResolvedReference

	if mg.Spec.ForProvider.RestoreToPointInTime != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RestoreToPointInTime.SourceID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.RestoreToPointInTime.SourceIDRef,
			Selector:     mg.Spec.ForProvider.RestoreToPointInTime.SourceIDSelector,
			To: reference.To{
				List:    &ServiceList{},
				Managed: &Service{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.RestoreToPointInTime.SourceID")
		}
		mg.Spec.ForProvider.RestoreToPointInTime.SourceID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.RestoreToPointInTime.SourceIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ReadReplicaOf),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ReadReplicaOfRef,
		Selector:     mg.Spec.InitProvider.ReadReplicaOfSelector,
		To: reference.To{
			List:    &ServiceList{},
			Managed: &Service{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ReadReplicaOf")
	}
	mg.Spec.InitProvider.ReadReplicaOf = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ReadReplicaOfRef = rsp.ResolvedReference

	if mg.Spec.InitProvider.RestoreToPointInTime != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.RestoreToPointInTime.SourceID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.RestoreToPointInTime.SourceIDRef,
			Selector:     mg.Spec.InitProvider.RestoreToPointInTime.SourceIDSelector,
			To: reference.To{
				List:    &ServiceList{},
				Managed: &Service{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.RestoreToPointInTime.SourceID")
		}
		mg.Spec.InitProvider.RestoreToPointInTime.SourceID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.RestoreToPointInTime.SourceIDRef = rsp.ResolvedReference

	}

	return nil
}
