// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ConnectionInitParameters struct {

	// (String) ClickHouse HTTP endpoint URL, e.g. https://clickhouse.example.com:8443.
	// ClickHouse HTTP endpoint URL, e.g. `https://clickhouse.example.com:8443`.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// specific ClickHouse settings. Must only contain alphanumeric characters and underscores.
	// Prefix for HyperDX-specific ClickHouse settings. Must only contain alphanumeric characters and underscores.
	HyperdxSettingPrefix *string `json:"hyperdxSettingPrefix,omitempty" tf:"hyperdx_setting_prefix,omitempty"`

	// (String) Display name for the connection.
	// Display name for the connection.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// sends the configured password.
	// ClickHouse password. The API never returns the password, so drift in this attribute cannot be detected. After import, the next apply re-sends the configured password.
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// compatible API endpoint, e.g. http://prometheus:9090. When set, PromQL queries are proxied to this endpoint.
	// Prometheus-compatible API endpoint, e.g. `http://prometheus:9090`. When set, PromQL queries are proxied to this endpoint.
	PrometheusEndpoint *string `json:"prometheusEndpoint,omitempty" tf:"prometheus_endpoint,omitempty"`

	// hdx-team header. Defaults to the API key's team. Only honored by multi-team (EE) deployments, which validate the API key's membership in the team; single-team (OSS) deployments ignore it. Changing this forces the connection to be replaced, since a connection ID is scoped to a single team.
	// Team ID to manage this connection under, sent as the `x-hdx-team` header. Defaults to the API key's team. Only honored by multi-team (EE) deployments, which validate the API key's membership in the team; single-team (OSS) deployments ignore it. Changing this forces the connection to be replaced, since a connection ID is scoped to a single team.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/namespaced/clickstack/v1alpha1.Team
	Team *string `json:"team,omitempty" tf:"team,omitempty"`

	// Reference to a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamRef *v2.NamespacedReference `json:"teamRef,omitempty" tf:"-"`

	// Selector for a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamSelector *v2.NamespacedSelector `json:"teamSelector,omitempty" tf:"-"`

	// (String) ClickHouse username.
	// ClickHouse username.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ConnectionObservation struct {

	// (String) ClickHouse HTTP endpoint URL, e.g. https://clickhouse.example.com:8443.
	// ClickHouse HTTP endpoint URL, e.g. `https://clickhouse.example.com:8443`.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// specific ClickHouse settings. Must only contain alphanumeric characters and underscores.
	// Prefix for HyperDX-specific ClickHouse settings. Must only contain alphanumeric characters and underscores.
	HyperdxSettingPrefix *string `json:"hyperdxSettingPrefix,omitempty" tf:"hyperdx_setting_prefix,omitempty"`

	// (String) Identifier of the connection.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Display name for the connection.
	// Display name for the connection.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// compatible API endpoint, e.g. http://prometheus:9090. When set, PromQL queries are proxied to this endpoint.
	// Prometheus-compatible API endpoint, e.g. `http://prometheus:9090`. When set, PromQL queries are proxied to this endpoint.
	PrometheusEndpoint *string `json:"prometheusEndpoint,omitempty" tf:"prometheus_endpoint,omitempty"`

	// hdx-team header. Defaults to the API key's team. Only honored by multi-team (EE) deployments, which validate the API key's membership in the team; single-team (OSS) deployments ignore it. Changing this forces the connection to be replaced, since a connection ID is scoped to a single team.
	// Team ID to manage this connection under, sent as the `x-hdx-team` header. Defaults to the API key's team. Only honored by multi-team (EE) deployments, which validate the API key's membership in the team; single-team (OSS) deployments ignore it. Changing this forces the connection to be replaced, since a connection ID is scoped to a single team.
	Team *string `json:"team,omitempty" tf:"team,omitempty"`

	// (String) ClickHouse username.
	// ClickHouse username.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ConnectionParameters struct {

	// (String) ClickHouse HTTP endpoint URL, e.g. https://clickhouse.example.com:8443.
	// ClickHouse HTTP endpoint URL, e.g. `https://clickhouse.example.com:8443`.
	// +kubebuilder:validation:Optional
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// specific ClickHouse settings. Must only contain alphanumeric characters and underscores.
	// Prefix for HyperDX-specific ClickHouse settings. Must only contain alphanumeric characters and underscores.
	// +kubebuilder:validation:Optional
	HyperdxSettingPrefix *string `json:"hyperdxSettingPrefix,omitempty" tf:"hyperdx_setting_prefix,omitempty"`

	// (String) Display name for the connection.
	// Display name for the connection.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// sends the configured password.
	// ClickHouse password. The API never returns the password, so drift in this attribute cannot be detected. After import, the next apply re-sends the configured password.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// compatible API endpoint, e.g. http://prometheus:9090. When set, PromQL queries are proxied to this endpoint.
	// Prometheus-compatible API endpoint, e.g. `http://prometheus:9090`. When set, PromQL queries are proxied to this endpoint.
	// +kubebuilder:validation:Optional
	PrometheusEndpoint *string `json:"prometheusEndpoint,omitempty" tf:"prometheus_endpoint,omitempty"`

	// hdx-team header. Defaults to the API key's team. Only honored by multi-team (EE) deployments, which validate the API key's membership in the team; single-team (OSS) deployments ignore it. Changing this forces the connection to be replaced, since a connection ID is scoped to a single team.
	// Team ID to manage this connection under, sent as the `x-hdx-team` header. Defaults to the API key's team. Only honored by multi-team (EE) deployments, which validate the API key's membership in the team; single-team (OSS) deployments ignore it. Changing this forces the connection to be replaced, since a connection ID is scoped to a single team.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/namespaced/clickstack/v1alpha1.Team
	// +kubebuilder:validation:Optional
	Team *string `json:"team,omitempty" tf:"team,omitempty"`

	// Reference to a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamRef *v2.NamespacedReference `json:"teamRef,omitempty" tf:"-"`

	// Selector for a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamSelector *v2.NamespacedSelector `json:"teamSelector,omitempty" tf:"-"`

	// (String) ClickHouse username.
	// ClickHouse username.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// ConnectionSpec defines the desired state of Connection
type ConnectionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ConnectionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConnectionInitParameters `json:"initProvider,omitempty"`
}

// ConnectionStatus defines the observed state of Connection.
type ConnectionStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ConnectionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Connection is the Schema for the Connections API. Manages a ClickHouse connection in ClickStack. Connections hold the credentials and endpoint used by sources to query ClickHouse. Note: on ClickHouse Cloud, connections are managed by ClickHouse Cloud and cannot be created, changed, or deleted through this resource; this resource is for self-hosted ClickStack. Reference an existing Cloud connection by its ID from clickhouse_clickstack_source.connection_id instead.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,clickhouse}
type Connection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.host) || (has(self.initProvider) && has(self.initProvider.host))",message="spec.forProvider.host is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   ConnectionSpec   `json:"spec"`
	Status ConnectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConnectionList contains a list of Connections
type ConnectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Connection `json:"items"`
}

// Repository type metadata.
var (
	Connection_Kind             = "Connection"
	Connection_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Connection_Kind}.String()
	Connection_KindAPIVersion   = Connection_Kind + "." + CRDGroupVersion.String()
	Connection_GroupVersionKind = CRDGroupVersion.WithKind(Connection_Kind)
)

func init() {
	SchemeBuilder.Register(&Connection{}, &ConnectionList{})
}
