// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type WebhookInitParameters struct {

	// (String, Sensitive) Request body template for generic and incidentio services. Not allowed for the slack service.
	// Request body template for `generic` and `incidentio` services. Not allowed for the `slack` service.
	BodySecretRef *v2.LocalSecretKeySelector `json:"bodySecretRef,omitempty" tf:"-"`

	// (String) Optional description of the webhook.
	// Optional description of the webhook.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Headers map[string]*string `json:"headersSecretRef,omitempty" tf:"-"`

	// only headers to be re-sent to the API. Note: this re-sends the CURRENT headers value; it does NOT clear the secret. Omitting headers leaves the last-sent value in place server-side — clearing a secret is not supported through this resource; recreate the webhook to remove it.
	// Arbitrary value that, when changed, forces the write-only `headers` to be re-sent to the API. Note: this re-sends the CURRENT `headers` value; it does NOT clear the secret. Omitting `headers` leaves the last-sent value in place server-side — clearing a secret is not supported through this resource; recreate the webhook to remove it.
	HeadersVersion *string `json:"headersVersion,omitempty" tf:"headers_version,omitempty"`

	// (String) Display name for the webhook. Must be unique per service within a team.
	// Display name for the webhook. Must be unique per service within a team.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	QueryParams map[string]*string `json:"queryParamsSecretRef,omitempty" tf:"-"`

	// only query_params to be re-sent to the API. As with headers_version, it re-sends the current value and cannot clear the secret; recreate the webhook to remove it.
	// Arbitrary value that, when changed, forces the write-only `query_params` to be re-sent to the API. As with `headers_version`, it re-sends the current value and cannot clear the secret; recreate the webhook to remove it.
	QueryParamsVersion *string `json:"queryParamsVersion,omitempty" tf:"query_params_version,omitempty"`

	// (String) Webhook service: one of slack, generic, or incidentio.
	// Webhook service: one of `slack`, `generic`, or `incidentio`.
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// hdx-team header. Defaults to the API key's team. Changing this forces the webhook to be replaced.
	// Team ID to manage this webhook under, sent as the `x-hdx-team` header. Defaults to the API key's team. Changing this forces the webhook to be replaced.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/namespaced/clickstack/v1alpha1.Team
	Team *string `json:"team,omitempty" tf:"team,omitempty"`

	// Reference to a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamRef *v2.NamespacedReference `json:"teamRef,omitempty" tf:"-"`

	// Selector for a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamSelector *v2.NamespacedSelector `json:"teamSelector,omitempty" tf:"-"`

	// webhook URLs embed a channel token. Private-IP/SSRF validation is enforced server-side.
	// Destination URL the ClickStack server calls. Marked sensitive because Slack incoming-webhook URLs embed a channel token. Private-IP/SSRF validation is enforced server-side.
	URLSecretRef v2.LocalSecretKeySelector `json:"urlSecretRef" tf:"-"`
}

type WebhookObservation struct {

	// (String) Optional description of the webhook.
	// Optional description of the webhook.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// only headers to be re-sent to the API. Note: this re-sends the CURRENT headers value; it does NOT clear the secret. Omitting headers leaves the last-sent value in place server-side — clearing a secret is not supported through this resource; recreate the webhook to remove it.
	// Arbitrary value that, when changed, forces the write-only `headers` to be re-sent to the API. Note: this re-sends the CURRENT `headers` value; it does NOT clear the secret. Omitting `headers` leaves the last-sent value in place server-side — clearing a secret is not supported through this resource; recreate the webhook to remove it.
	HeadersVersion *string `json:"headersVersion,omitempty" tf:"headers_version,omitempty"`

	// (String) Identifier of the webhook.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Display name for the webhook. Must be unique per service within a team.
	// Display name for the webhook. Must be unique per service within a team.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// only query_params to be re-sent to the API. As with headers_version, it re-sends the current value and cannot clear the secret; recreate the webhook to remove it.
	// Arbitrary value that, when changed, forces the write-only `query_params` to be re-sent to the API. As with `headers_version`, it re-sends the current value and cannot clear the secret; recreate the webhook to remove it.
	QueryParamsVersion *string `json:"queryParamsVersion,omitempty" tf:"query_params_version,omitempty"`

	// (String) Webhook service: one of slack, generic, or incidentio.
	// Webhook service: one of `slack`, `generic`, or `incidentio`.
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// hdx-team header. Defaults to the API key's team. Changing this forces the webhook to be replaced.
	// Team ID to manage this webhook under, sent as the `x-hdx-team` header. Defaults to the API key's team. Changing this forces the webhook to be replaced.
	Team *string `json:"team,omitempty" tf:"team,omitempty"`
}

type WebhookParameters struct {

	// (String, Sensitive) Request body template for generic and incidentio services. Not allowed for the slack service.
	// Request body template for `generic` and `incidentio` services. Not allowed for the `slack` service.
	// +kubebuilder:validation:Optional
	BodySecretRef *v2.LocalSecretKeySelector `json:"bodySecretRef,omitempty" tf:"-"`

	// (String) Optional description of the webhook.
	// Optional description of the webhook.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// only) Write-only HTTP headers sent with the webhook request (e.g. an Authorization token). Never stored in state or returned by the API. Not allowed for the slack service. Bump headers_version to re-send after a change. The server keeps the last-sent headers when this field is omitted, EXCEPT when url or service changes — that clears any omitted secret, so re-supply headers (and bump headers_version) whenever you change the destination.
	// Write-only HTTP headers sent with the webhook request (e.g. an `Authorization` token). Never stored in state or returned by the API. Not allowed for the `slack` service. Bump `headers_version` to re-send after a change. The server keeps the last-sent headers when this field is omitted, EXCEPT when `url` or `service` changes — that clears any omitted secret, so re-supply headers (and bump `headers_version`) whenever you change the destination.
	// +kubebuilder:validation:Optional
	HeadersSecretRef *v2.LocalSecretReference `json:"headersSecretRef,omitempty" tf:"-"`

	// only headers to be re-sent to the API. Note: this re-sends the CURRENT headers value; it does NOT clear the secret. Omitting headers leaves the last-sent value in place server-side — clearing a secret is not supported through this resource; recreate the webhook to remove it.
	// Arbitrary value that, when changed, forces the write-only `headers` to be re-sent to the API. Note: this re-sends the CURRENT `headers` value; it does NOT clear the secret. Omitting `headers` leaves the last-sent value in place server-side — clearing a secret is not supported through this resource; recreate the webhook to remove it.
	// +kubebuilder:validation:Optional
	HeadersVersion *string `json:"headersVersion,omitempty" tf:"headers_version,omitempty"`

	// (String) Display name for the webhook. Must be unique per service within a team.
	// Display name for the webhook. Must be unique per service within a team.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// only) Write-only URL query parameters sent with the webhook request. Never stored in state or returned by the API. Not allowed for the slack service. Bump query_params_version to re-send after a change.
	// Write-only URL query parameters sent with the webhook request. Never stored in state or returned by the API. Not allowed for the `slack` service. Bump `query_params_version` to re-send after a change.
	// +kubebuilder:validation:Optional
	QueryParamsSecretRef *v2.LocalSecretReference `json:"queryParamsSecretRef,omitempty" tf:"-"`

	// only query_params to be re-sent to the API. As with headers_version, it re-sends the current value and cannot clear the secret; recreate the webhook to remove it.
	// Arbitrary value that, when changed, forces the write-only `query_params` to be re-sent to the API. As with `headers_version`, it re-sends the current value and cannot clear the secret; recreate the webhook to remove it.
	// +kubebuilder:validation:Optional
	QueryParamsVersion *string `json:"queryParamsVersion,omitempty" tf:"query_params_version,omitempty"`

	// (String) Webhook service: one of slack, generic, or incidentio.
	// Webhook service: one of `slack`, `generic`, or `incidentio`.
	// +kubebuilder:validation:Optional
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// hdx-team header. Defaults to the API key's team. Changing this forces the webhook to be replaced.
	// Team ID to manage this webhook under, sent as the `x-hdx-team` header. Defaults to the API key's team. Changing this forces the webhook to be replaced.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/namespaced/clickstack/v1alpha1.Team
	// +kubebuilder:validation:Optional
	Team *string `json:"team,omitempty" tf:"team,omitempty"`

	// Reference to a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamRef *v2.NamespacedReference `json:"teamRef,omitempty" tf:"-"`

	// Selector for a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamSelector *v2.NamespacedSelector `json:"teamSelector,omitempty" tf:"-"`

	// webhook URLs embed a channel token. Private-IP/SSRF validation is enforced server-side.
	// Destination URL the ClickStack server calls. Marked sensitive because Slack incoming-webhook URLs embed a channel token. Private-IP/SSRF validation is enforced server-side.
	// +kubebuilder:validation:Optional
	URLSecretRef v2.LocalSecretKeySelector `json:"urlSecretRef" tf:"-"`
}

// WebhookSpec defines the desired state of Webhook
type WebhookSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            WebhookParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WebhookInitParameters `json:"initProvider,omitempty"`
}

// WebhookStatus defines the observed state of Webhook.
type WebhookStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               WebhookObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Webhook is the Schema for the Webhooks API. Manages a ClickStack notification webhook (Slack, generic HTTP, or incident.io), used as the notification channel for alerts.11.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,clickhouse}
type Webhook struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.service) || (has(self.initProvider) && has(self.initProvider.service))",message="spec.forProvider.service is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.urlSecretRef)",message="spec.forProvider.urlSecretRef is a required parameter"
	Spec   WebhookSpec   `json:"spec"`
	Status WebhookStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WebhookList contains a list of Webhooks
type WebhookList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Webhook `json:"items"`
}

// Repository type metadata.
var (
	Webhook_Kind             = "Webhook"
	Webhook_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Webhook_Kind}.String()
	Webhook_KindAPIVersion   = Webhook_Kind + "." + CRDGroupVersion.String()
	Webhook_GroupVersionKind = CRDGroupVersion.WithKind(Webhook_Kind)
)

func init() {
	SchemeBuilder.Register(&Webhook{}, &WebhookList{})
}
