// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AlertInitParameters struct {

	// (Attributes) Notification channel for the alert. (see below for nested schema)
	Channel *ChannelInitParameters `json:"channel,omitempty" tf:"channel,omitempty"`

	// op (recreate the alert to fully reset it).
	// Optional expression to evaluate the alert per group. Sticky once set: the API keeps the previous value when the field is omitted and cannot clear it, so removing it from config is a no-op (recreate the alert to fully reset it).
	GroupBy *string `json:"groupBy,omitempty" tf:"group_by,omitempty"`

	// (String) Evaluation window: one of 1m, 5m, 15m, 30m, 1h, 6h, 12h, 1d.
	// Evaluation window: one of `1m`, `5m`, `15m`, `30m`, `1h`, `6h`, `12h`, `1d`.
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// 4096 characters).
	// Optional notification message template (1-4096 characters).
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// 512 characters).
	// Optional alert name (1-512 characters).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// 4096 characters).
	// Optional markdown note (1-4096 characters).
	Note *string `json:"note,omitempty" tf:"note,omitempty"`

	// (Number) Fire only after the condition holds for this many consecutive windows (>= 1).
	// Fire only after the condition holds for this many consecutive windows (>= 1).
	NumConsecutiveWindows *float64 `json:"numConsecutiveWindows,omitempty" tf:"num_consecutive_windows,omitempty"`

	// (String) ID of the saved search this alert evaluates.
	// ID of the saved search this alert evaluates.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickstack/v1alpha1.SavedSearch
	SavedSearchID *string `json:"savedSearchId,omitempty" tf:"saved_search_id,omitempty"`

	// Reference to a SavedSearch in clickstack to populate savedSearchId.
	// +kubebuilder:validation:Optional
	SavedSearchIDRef *v2.Reference `json:"savedSearchIdRef,omitempty" tf:"-"`

	// Selector for a SavedSearch in clickstack to populate savedSearchId.
	// +kubebuilder:validation:Optional
	SavedSearchIDSelector *v2.Selector `json:"savedSearchIdSelector,omitempty" tf:"-"`

	// 1439, and less than the interval). Mutually exclusive with schedule_start_at; setting one clears the other.
	// Offset window boundaries by this many minutes (0-1439, and less than the interval). Mutually exclusive with `schedule_start_at`; setting one clears the other.
	ScheduleOffsetMinutes *float64 `json:"scheduleOffsetMinutes,omitempty" tf:"schedule_offset_minutes,omitempty"`

	// zero schedule_offset_minutes; setting one clears the other.
	// Absolute UTC anchor (RFC3339) for window alignment. Mutually exclusive with a non-zero `schedule_offset_minutes`; setting one clears the other.
	ScheduleStartAt *string `json:"scheduleStartAt,omitempty" tf:"schedule_start_at,omitempty"`

	// hdx-team). Changing this forces the alert to be replaced.
	// Team ID to manage this alert under (`x-hdx-team`). Changing this forces the alert to be replaced.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickstack/v1alpha1.Team
	Team *string `json:"team,omitempty" tf:"team,omitempty"`

	// Reference to a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamRef *v2.Reference `json:"teamRef,omitempty" tf:"-"`

	// Selector for a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamSelector *v2.Selector `json:"teamSelector,omitempty" tf:"-"`

	// (Number) Threshold value the alert compares against. For range types (between/not_between) this is the lower bound.
	// Threshold value the alert compares against. For range types (`between`/`not_between`) this is the lower bound.
	Threshold *float64 `json:"threshold,omitempty" tf:"threshold,omitempty"`

	// (Number) Upper bound, required for between/not_between and ignored otherwise. Must be >= threshold.
	// Upper bound, required for `between`/`not_between` and ignored otherwise. Must be >= `threshold`.
	ThresholdMax *float64 `json:"thresholdMax,omitempty" tf:"threshold_max,omitempty"`

	// (String) Comparison type: one of above, below, above_exclusive, below_or_equal, equal, not_equal, between, not_between.
	// Comparison type: one of `above`, `below`, `above_exclusive`, `below_or_equal`, `equal`, `not_equal`, `between`, `not_between`.
	ThresholdType *string `json:"thresholdType,omitempty" tf:"threshold_type,omitempty"`
}

type AlertObservation struct {

	// (Attributes) Notification channel for the alert. (see below for nested schema)
	Channel *ChannelObservation `json:"channel,omitempty" tf:"channel,omitempty"`

	// op (recreate the alert to fully reset it).
	// Optional expression to evaluate the alert per group. Sticky once set: the API keeps the previous value when the field is omitted and cannot clear it, so removing it from config is a no-op (recreate the alert to fully reset it).
	GroupBy *string `json:"groupBy,omitempty" tf:"group_by,omitempty"`

	// (String) Identifier of the alert.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Evaluation window: one of 1m, 5m, 15m, 30m, 1h, 6h, 12h, 1d.
	// Evaluation window: one of `1m`, `5m`, `15m`, `30m`, `1h`, `6h`, `12h`, `1d`.
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// 4096 characters).
	// Optional notification message template (1-4096 characters).
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// 512 characters).
	// Optional alert name (1-512 characters).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// 4096 characters).
	// Optional markdown note (1-4096 characters).
	Note *string `json:"note,omitempty" tf:"note,omitempty"`

	// (Number) Fire only after the condition holds for this many consecutive windows (>= 1).
	// Fire only after the condition holds for this many consecutive windows (>= 1).
	NumConsecutiveWindows *float64 `json:"numConsecutiveWindows,omitempty" tf:"num_consecutive_windows,omitempty"`

	// (String) ID of the saved search this alert evaluates.
	// ID of the saved search this alert evaluates.
	SavedSearchID *string `json:"savedSearchId,omitempty" tf:"saved_search_id,omitempty"`

	// 1439, and less than the interval). Mutually exclusive with schedule_start_at; setting one clears the other.
	// Offset window boundaries by this many minutes (0-1439, and less than the interval). Mutually exclusive with `schedule_start_at`; setting one clears the other.
	ScheduleOffsetMinutes *float64 `json:"scheduleOffsetMinutes,omitempty" tf:"schedule_offset_minutes,omitempty"`

	// zero schedule_offset_minutes; setting one clears the other.
	// Absolute UTC anchor (RFC3339) for window alignment. Mutually exclusive with a non-zero `schedule_offset_minutes`; setting one clears the other.
	ScheduleStartAt *string `json:"scheduleStartAt,omitempty" tf:"schedule_start_at,omitempty"`

	// hdx-team). Changing this forces the alert to be replaced.
	// Team ID to manage this alert under (`x-hdx-team`). Changing this forces the alert to be replaced.
	Team *string `json:"team,omitempty" tf:"team,omitempty"`

	// (Number) Threshold value the alert compares against. For range types (between/not_between) this is the lower bound.
	// Threshold value the alert compares against. For range types (`between`/`not_between`) this is the lower bound.
	Threshold *float64 `json:"threshold,omitempty" tf:"threshold,omitempty"`

	// (Number) Upper bound, required for between/not_between and ignored otherwise. Must be >= threshold.
	// Upper bound, required for `between`/`not_between` and ignored otherwise. Must be >= `threshold`.
	ThresholdMax *float64 `json:"thresholdMax,omitempty" tf:"threshold_max,omitempty"`

	// (String) Comparison type: one of above, below, above_exclusive, below_or_equal, equal, not_equal, between, not_between.
	// Comparison type: one of `above`, `below`, `above_exclusive`, `below_or_equal`, `equal`, `not_equal`, `between`, `not_between`.
	ThresholdType *string `json:"thresholdType,omitempty" tf:"threshold_type,omitempty"`
}

type AlertParameters struct {

	// (Attributes) Notification channel for the alert. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Channel *ChannelParameters `json:"channel,omitempty" tf:"channel,omitempty"`

	// op (recreate the alert to fully reset it).
	// Optional expression to evaluate the alert per group. Sticky once set: the API keeps the previous value when the field is omitted and cannot clear it, so removing it from config is a no-op (recreate the alert to fully reset it).
	// +kubebuilder:validation:Optional
	GroupBy *string `json:"groupBy,omitempty" tf:"group_by,omitempty"`

	// (String) Evaluation window: one of 1m, 5m, 15m, 30m, 1h, 6h, 12h, 1d.
	// Evaluation window: one of `1m`, `5m`, `15m`, `30m`, `1h`, `6h`, `12h`, `1d`.
	// +kubebuilder:validation:Optional
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// 4096 characters).
	// Optional notification message template (1-4096 characters).
	// +kubebuilder:validation:Optional
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// 512 characters).
	// Optional alert name (1-512 characters).
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// 4096 characters).
	// Optional markdown note (1-4096 characters).
	// +kubebuilder:validation:Optional
	Note *string `json:"note,omitempty" tf:"note,omitempty"`

	// (Number) Fire only after the condition holds for this many consecutive windows (>= 1).
	// Fire only after the condition holds for this many consecutive windows (>= 1).
	// +kubebuilder:validation:Optional
	NumConsecutiveWindows *float64 `json:"numConsecutiveWindows,omitempty" tf:"num_consecutive_windows,omitempty"`

	// (String) ID of the saved search this alert evaluates.
	// ID of the saved search this alert evaluates.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickstack/v1alpha1.SavedSearch
	// +kubebuilder:validation:Optional
	SavedSearchID *string `json:"savedSearchId,omitempty" tf:"saved_search_id,omitempty"`

	// Reference to a SavedSearch in clickstack to populate savedSearchId.
	// +kubebuilder:validation:Optional
	SavedSearchIDRef *v2.Reference `json:"savedSearchIdRef,omitempty" tf:"-"`

	// Selector for a SavedSearch in clickstack to populate savedSearchId.
	// +kubebuilder:validation:Optional
	SavedSearchIDSelector *v2.Selector `json:"savedSearchIdSelector,omitempty" tf:"-"`

	// 1439, and less than the interval). Mutually exclusive with schedule_start_at; setting one clears the other.
	// Offset window boundaries by this many minutes (0-1439, and less than the interval). Mutually exclusive with `schedule_start_at`; setting one clears the other.
	// +kubebuilder:validation:Optional
	ScheduleOffsetMinutes *float64 `json:"scheduleOffsetMinutes,omitempty" tf:"schedule_offset_minutes,omitempty"`

	// zero schedule_offset_minutes; setting one clears the other.
	// Absolute UTC anchor (RFC3339) for window alignment. Mutually exclusive with a non-zero `schedule_offset_minutes`; setting one clears the other.
	// +kubebuilder:validation:Optional
	ScheduleStartAt *string `json:"scheduleStartAt,omitempty" tf:"schedule_start_at,omitempty"`

	// hdx-team). Changing this forces the alert to be replaced.
	// Team ID to manage this alert under (`x-hdx-team`). Changing this forces the alert to be replaced.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickstack/v1alpha1.Team
	// +kubebuilder:validation:Optional
	Team *string `json:"team,omitempty" tf:"team,omitempty"`

	// Reference to a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamRef *v2.Reference `json:"teamRef,omitempty" tf:"-"`

	// Selector for a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamSelector *v2.Selector `json:"teamSelector,omitempty" tf:"-"`

	// (Number) Threshold value the alert compares against. For range types (between/not_between) this is the lower bound.
	// Threshold value the alert compares against. For range types (`between`/`not_between`) this is the lower bound.
	// +kubebuilder:validation:Optional
	Threshold *float64 `json:"threshold,omitempty" tf:"threshold,omitempty"`

	// (Number) Upper bound, required for between/not_between and ignored otherwise. Must be >= threshold.
	// Upper bound, required for `between`/`not_between` and ignored otherwise. Must be >= `threshold`.
	// +kubebuilder:validation:Optional
	ThresholdMax *float64 `json:"thresholdMax,omitempty" tf:"threshold_max,omitempty"`

	// (String) Comparison type: one of above, below, above_exclusive, below_or_equal, equal, not_equal, between, not_between.
	// Comparison type: one of `above`, `below`, `above_exclusive`, `below_or_equal`, `equal`, `not_equal`, `between`, `not_between`.
	// +kubebuilder:validation:Optional
	ThresholdType *string `json:"thresholdType,omitempty" tf:"threshold_type,omitempty"`
}

type ChannelInitParameters struct {

	// (String) Channel type. Currently only webhook is supported.
	// Channel type. Currently only `webhook` is supported.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) ID of the webhook to notify. Required when type is webhook.
	// ID of the webhook to notify. Required when `type` is `webhook`.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickstack/v1alpha1.Webhook
	WebhookID *string `json:"webhookId,omitempty" tf:"webhook_id,omitempty"`

	// Reference to a Webhook in clickstack to populate webhookId.
	// +kubebuilder:validation:Optional
	WebhookIDRef *v2.Reference `json:"webhookIdRef,omitempty" tf:"-"`

	// Selector for a Webhook in clickstack to populate webhookId.
	// +kubebuilder:validation:Optional
	WebhookIDSelector *v2.Selector `json:"webhookIdSelector,omitempty" tf:"-"`
}

type ChannelObservation struct {

	// (String) Channel type. Currently only webhook is supported.
	// Channel type. Currently only `webhook` is supported.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) ID of the webhook to notify. Required when type is webhook.
	// ID of the webhook to notify. Required when `type` is `webhook`.
	WebhookID *string `json:"webhookId,omitempty" tf:"webhook_id,omitempty"`
}

type ChannelParameters struct {

	// (String) Channel type. Currently only webhook is supported.
	// Channel type. Currently only `webhook` is supported.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// (String) ID of the webhook to notify. Required when type is webhook.
	// ID of the webhook to notify. Required when `type` is `webhook`.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickstack/v1alpha1.Webhook
	// +kubebuilder:validation:Optional
	WebhookID *string `json:"webhookId,omitempty" tf:"webhook_id,omitempty"`

	// Reference to a Webhook in clickstack to populate webhookId.
	// +kubebuilder:validation:Optional
	WebhookIDRef *v2.Reference `json:"webhookIdRef,omitempty" tf:"-"`

	// Selector for a Webhook in clickstack to populate webhookId.
	// +kubebuilder:validation:Optional
	WebhookIDSelector *v2.Selector `json:"webhookIdSelector,omitempty" tf:"-"`
}

// AlertSpec defines the desired state of Alert
type AlertSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   AlertParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AlertInitParameters `json:"initProvider,omitempty"`
}

// AlertStatus defines the observed state of Alert.
type AlertStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AlertObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Alert is the Schema for the Alerts API. Manages a ClickStack alert that evaluates a saved search on a schedule and notifies through a channel when a threshold is crossed. Alerts are threshold-based (there is no anomaly mode). Configuration is validated at plan time; those rules mirror the ClickStack server contract on a best-effort basis, so a server-side rule change may make the plan-time checks slightly stale until a new provider release.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhouse}
type Alert struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.channel) || (has(self.initProvider) && has(self.initProvider.channel))",message="spec.forProvider.channel is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.interval) || (has(self.initProvider) && has(self.initProvider.interval))",message="spec.forProvider.interval is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.threshold) || (has(self.initProvider) && has(self.initProvider.threshold))",message="spec.forProvider.threshold is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.thresholdType) || (has(self.initProvider) && has(self.initProvider.thresholdType))",message="spec.forProvider.thresholdType is a required parameter"
	Spec   AlertSpec   `json:"spec"`
	Status AlertStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AlertList contains a list of Alerts
type AlertList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Alert `json:"items"`
}

// Repository type metadata.
var (
	Alert_Kind             = "Alert"
	Alert_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Alert_Kind}.String()
	Alert_KindAPIVersion   = Alert_Kind + "." + CRDGroupVersion.String()
	Alert_GroupVersionKind = CRDGroupVersion.WithKind(Alert_Kind)
)

func init() {
	SchemeBuilder.Register(&Alert{}, &AlertList{})
}
