// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DashboardInitParameters struct {

	// (String) The dashboard body as a JSON string, in the v2 API format. Use jsonencode(...) or file(...).
	// The dashboard body as a JSON string, in the v2 API format. Use `jsonencode(...)` or `file(...)`.
	DashboardJSON *string `json:"dashboardJson,omitempty" tf:"dashboard_json,omitempty"`

	// hdx-team). Changing this forces replacement.
	// Team ID to manage this dashboard under (`x-hdx-team`). Changing this forces replacement.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickstack/v1alpha1.Team
	Team *string `json:"team,omitempty" tf:"team,omitempty"`

	// Reference to a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamRef *v2.Reference `json:"teamRef,omitempty" tf:"-"`

	// Selector for a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamSelector *v2.Selector `json:"teamSelector,omitempty" tf:"-"`
}

type DashboardObservation struct {

	// (String) The dashboard body as a JSON string, in the v2 API format. Use jsonencode(...) or file(...).
	// The dashboard body as a JSON string, in the v2 API format. Use `jsonencode(...)` or `file(...)`.
	DashboardJSON *string `json:"dashboardJson,omitempty" tf:"dashboard_json,omitempty"`

	// (String) Identifier of the dashboard.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// canonical dashboard body returned by the API (defaults applied, server-assigned tile IDs).
	// Server-canonical dashboard body returned by the API (defaults applied, server-assigned tile IDs).
	NormalizedJSON *string `json:"normalizedJson,omitempty" tf:"normalized_json,omitempty"`

	// hdx-team). Changing this forces replacement.
	// Team ID to manage this dashboard under (`x-hdx-team`). Changing this forces replacement.
	Team *string `json:"team,omitempty" tf:"team,omitempty"`
}

type DashboardParameters struct {

	// (String) The dashboard body as a JSON string, in the v2 API format. Use jsonencode(...) or file(...).
	// The dashboard body as a JSON string, in the v2 API format. Use `jsonencode(...)` or `file(...)`.
	// +kubebuilder:validation:Optional
	DashboardJSON *string `json:"dashboardJson,omitempty" tf:"dashboard_json,omitempty"`

	// hdx-team). Changing this forces replacement.
	// Team ID to manage this dashboard under (`x-hdx-team`). Changing this forces replacement.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickstack/v1alpha1.Team
	// +kubebuilder:validation:Optional
	Team *string `json:"team,omitempty" tf:"team,omitempty"`

	// Reference to a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamRef *v2.Reference `json:"teamRef,omitempty" tf:"-"`

	// Selector for a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamSelector *v2.Selector `json:"teamSelector,omitempty" tf:"-"`
}

// DashboardSpec defines the desired state of Dashboard
type DashboardSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   DashboardParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DashboardInitParameters `json:"initProvider,omitempty"`
}

// DashboardStatus defines the observed state of Dashboard.
type DashboardStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DashboardObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Dashboard is the Schema for the Dashboards API. Manages a ClickStack dashboard from a JSON document (the v2 API dashboard body: name, tiles, tags, filters, savedQuery, containers). The JSON is validated at plan time against the ClickStack API when the validate endpoint is available. PromQL tiles are not supported by the API and cannot be managed here.g. edits in the UI). Tile alerts (alerts bound to a dashboard tile) are not managed by this resource. Tiles with duplicate or blank names, or renamed between applies, fall back to positional matching and may lose their alert; pin an explicit id on such tiles if you manage tile alerts in the UI.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhouse}
type Dashboard struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dashboardJson) || (has(self.initProvider) && has(self.initProvider.dashboardJson))",message="spec.forProvider.dashboardJson is a required parameter"
	Spec   DashboardSpec   `json:"spec"`
	Status DashboardStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DashboardList contains a list of Dashboards
type DashboardList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Dashboard `json:"items"`
}

// Repository type metadata.
var (
	Dashboard_Kind             = "Dashboard"
	Dashboard_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Dashboard_Kind}.String()
	Dashboard_KindAPIVersion   = Dashboard_Kind + "." + CRDGroupVersion.String()
	Dashboard_GroupVersionKind = CRDGroupVersion.WithKind(Dashboard_Kind)
)

func init() {
	SchemeBuilder.Register(&Dashboard{}, &DashboardList{})
}
