// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type TeamMemberInitParameters struct {

	// (String) Email address of the member. Changing this forces the member to be replaced.
	// Email address of the member. Changing this forces the member to be replaced.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) Display name used when creating a pending invitation. Changing this forces the member to be replaced.
	// Display name used when creating a pending invitation. Changing this forces the member to be replaced.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the role to assign to the member. Use the clickstack_role resource or data source to obtain it. Omit on OSS deployments, which have no RBAC and ignore the role. When omitted, the role assigned by the server (e.g. the team's default role on RBAC deployments) is tracked in state.
	// ID of the role to assign to the member. Use the `clickstack_role` resource or data source to obtain it. Omit on OSS deployments, which have no RBAC and ignore the role. When omitted, the role assigned by the server (e.g. the team's default role on RBAC deployments) is tracked in state.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickstack/v1alpha1.Role
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// Reference to a Role in clickstack to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDRef *v2.Reference `json:"roleIdRef,omitempty" tf:"-"`

	// Selector for a Role in clickstack to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDSelector *v2.Selector `json:"roleIdSelector,omitempty" tf:"-"`

	// hdx-team header. Defaults to the API key's team. Changing this forces the member to be replaced.
	// Team ID to manage this member under, sent as the `x-hdx-team` header. Defaults to the API key's team. Changing this forces the member to be replaced.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickstack/v1alpha1.Team
	Team *string `json:"team,omitempty" tf:"team,omitempty"`

	// Reference to a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamRef *v2.Reference `json:"teamRef,omitempty" tf:"-"`

	// Selector for a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamSelector *v2.Selector `json:"teamSelector,omitempty" tf:"-"`
}

type TeamMemberObservation struct {

	// (String) Email address of the member. Changing this forces the member to be replaced.
	// Email address of the member. Changing this forces the member to be replaced.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) Identifier of the member. For an active member this is their user ID; for a pending invitation this is the invitation ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Display name used when creating a pending invitation. Changing this forces the member to be replaced.
	// Display name used when creating a pending invitation. Changing this forces the member to be replaced.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the role to assign to the member. Use the clickstack_role resource or data source to obtain it. Omit on OSS deployments, which have no RBAC and ignore the role. When omitted, the role assigned by the server (e.g. the team's default role on RBAC deployments) is tracked in state.
	// ID of the role to assign to the member. Use the `clickstack_role` resource or data source to obtain it. Omit on OSS deployments, which have no RBAC and ignore the role. When omitted, the role assigned by the server (e.g. the team's default role on RBAC deployments) is tracked in state.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// (String) Membership status: active (account assigned the role) or pending (invitation outstanding).
	// Membership status: `active` (account assigned the role) or `pending` (invitation outstanding).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// hdx-team header. Defaults to the API key's team. Changing this forces the member to be replaced.
	// Team ID to manage this member under, sent as the `x-hdx-team` header. Defaults to the API key's team. Changing this forces the member to be replaced.
	Team *string `json:"team,omitempty" tf:"team,omitempty"`
}

type TeamMemberParameters struct {

	// (String) Email address of the member. Changing this forces the member to be replaced.
	// Email address of the member. Changing this forces the member to be replaced.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) Display name used when creating a pending invitation. Changing this forces the member to be replaced.
	// Display name used when creating a pending invitation. Changing this forces the member to be replaced.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the role to assign to the member. Use the clickstack_role resource or data source to obtain it. Omit on OSS deployments, which have no RBAC and ignore the role. When omitted, the role assigned by the server (e.g. the team's default role on RBAC deployments) is tracked in state.
	// ID of the role to assign to the member. Use the `clickstack_role` resource or data source to obtain it. Omit on OSS deployments, which have no RBAC and ignore the role. When omitted, the role assigned by the server (e.g. the team's default role on RBAC deployments) is tracked in state.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickstack/v1alpha1.Role
	// +kubebuilder:validation:Optional
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// Reference to a Role in clickstack to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDRef *v2.Reference `json:"roleIdRef,omitempty" tf:"-"`

	// Selector for a Role in clickstack to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDSelector *v2.Selector `json:"roleIdSelector,omitempty" tf:"-"`

	// hdx-team header. Defaults to the API key's team. Changing this forces the member to be replaced.
	// Team ID to manage this member under, sent as the `x-hdx-team` header. Defaults to the API key's team. Changing this forces the member to be replaced.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhouse/apis/cluster/clickstack/v1alpha1.Team
	// +kubebuilder:validation:Optional
	Team *string `json:"team,omitempty" tf:"team,omitempty"`

	// Reference to a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamRef *v2.Reference `json:"teamRef,omitempty" tf:"-"`

	// Selector for a Team in clickstack to populate team.
	// +kubebuilder:validation:Optional
	TeamSelector *v2.Selector `json:"teamSelector,omitempty" tf:"-"`
}

// TeamMemberSpec defines the desired state of TeamMember
type TeamMemberSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   TeamMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamMemberInitParameters `json:"initProvider,omitempty"`
}

// TeamMemberStatus defines the observed state of TeamMember.
type TeamMemberStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               TeamMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TeamMember is the Schema for the TeamMembers API. Manages a team member and their RBAC role. On create the member is invited: existing accounts are assigned the role immediately (status = active), otherwise a pending invitation is created (status = pending) and invite_url is populated. Note: on ClickHouse Cloud, team membership is managed through ClickHouse Cloud (the clickhouse_role_assignment resource), not the ClickStack API; this resource is for self-hosted ClickStack.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhouse}
type TeamMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.email) || (has(self.initProvider) && has(self.initProvider.email))",message="spec.forProvider.email is a required parameter"
	Spec   TeamMemberSpec   `json:"spec"`
	Status TeamMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamMemberList contains a list of TeamMembers
type TeamMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TeamMember `json:"items"`
}

// Repository type metadata.
var (
	TeamMember_Kind             = "TeamMember"
	TeamMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TeamMember_Kind}.String()
	TeamMember_KindAPIVersion   = TeamMember_Kind + "." + CRDGroupVersion.String()
	TeamMember_GroupVersionKind = CRDGroupVersion.WithKind(TeamMember_Kind)
)

func init() {
	SchemeBuilder.Register(&TeamMember{}, &TeamMemberList{})
}
